---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: proxy-core
  namespace: proxy
  labels: &l
    kustomization.flux.home.arpa/name: proxy-core
spec:
  path: ./kube/deploy/services/proxy/core/
  interval: 1h
  prune: false
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  postBuild:
    substituteFrom:
      - kind: Secret
        name: proxy-secrets
        optional: false
