---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-com.${EXTERNAL_DOMAIN}
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  secretName: tls-cert-com.${EXTERNAL_DOMAIN}
  issuerRef:
    name: letsencrypt-prod-${EXTERNAL_DOMAIN}
    kind: ClusterIssuer
  dnsNames: ['com.${EXTERNAL_DOMAIN}']
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: &n element
spec:
  routes:
    - match: Host(`com.${EXTERNAL_DOMAIN}`)
      kind: Rule
      services:
        - name: *n
          port: 80
      middlewares:
        - name: compress
          namespace: ingress
  tls:
    secretName: tls-cert-com.${EXTERNAL_DOMAIN}
    domains:
      - main: com.${EXTERNAL_DOMAIN}
