---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAgent
metadata:
  name: main
spec:
  selectAllByDefault: true
  replicaCount: 2
  remoteWrite:
    - url: http://vmsingle-main:8429/api/v1/write
