---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMSingle
metadata:
  name: main
spec:
  retentionPeriod: '12'
  extraArgs:
    dedup.minScrapeInterval: 60s
  removePvcAfterDelete: false
  storage:
    accessModes: [ReadWriteOnce]
    resources:
      requests:
        storage: 100Gi
