---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n cilium-app
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/core/1-kube-system/cilium/app
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: kube-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n cilium-configs
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/core/1-kube-system/cilium/configs
  interval: 1h
  prune: false
  wait: true
  dependsOn:
    - name: cilium-app
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: kube-system
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cilium-secrets
        optional: false

---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n cilium-netpols
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/core/1-kube-system/cilium/netpols
  interval: 1h
  prune: false
  wait: true
  dependsOn:
    - name: cilium-app
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  postBuild:
    substituteFrom:
      - kind: Secret
        name: cilium-secrets
        optional: false
