---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n memos
  labels:
    helm.flux.home.arpa/app-template: true
spec:
  values:
    global:
      annotations:
        k8up.io/backup: 'true'
    controllers:
      memos:
        type: deployment
        strategy: Recreate
        replicas: 1
        pod:
          labels:
            traefik.home.arpa/ingress: allow
            egress.home.arpa/internet-https: allow
            sso.home.arpa/egress: allow
        containers:
          application:
            image:
              repository: neosmemo/memos
              tag: '0.21'
            resources:  # TODO refine
              limits:
                cpu: 1
                memory: 500Mi
              requests:
                cpu: 1m
                memory: 1Mi
            env:
              TZ: Europe/Paris
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
        globalMounts:
          - path: /var/opt/memos
    service:
      http:
        controller: *n
        ports:
          http:
            port: 5230
