---
apiVersion: grafana.integreatly.org/v1beta1
kind: Grafana
metadata:
  name: grafana-main
  labels:
    instance: grafana-main
spec:
  deployment:
    spec:
      template:
        metadata:
          labels:
            egress.home.arpa/internet: allow
            traefik.home.arpa/ingress: allow
            managedBy: grafana-operator

  service:
    metadata:
      labels:
        managed-by: grafana-operator

  config:
    server:
      root_url: https://graf.${DOMAIN_PUBLIC}

    auth.generic_oauth:
      enabled: "true"
      name: "Authelia SSO"
      icon: signin
      allow_sign_up: "true"
      client_id: ${GRAFANA_OICD_CLIENT_ID}
      client_secret: ${GRAFANA_OICD_CLIENT_SECRET}
      scopes: "openid profile email groups"
      empty_scopes: "false"
      login_attribute_path: preferred_username
      name_attribute_path: name
      groups_attribute_path: groups
      auth_url: https://sso.${DOMAIN_PUBLIC}/api/oidc/authorization
      token_url: https://sso.${DOMAIN_PUBLIC}/api/oidc/token
      api_url: https://sso.${DOMAIN_PUBLIC}/api/oidc/userinfo
      role_attribute_path: "contains(groups, 'admins') && 'Admin' || contains(groups, 'devs') && 'Viewer'"
      use_pkce: "true"
