---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n reflector-operator
  labels:
    helm.flux.home.arpa/crds-lifecycle: CreateReplace
spec:
  chart:
    spec:
      chart: reflector
      version: 7.1.262
      sourceRef:
        kind: HelmRepository
        name: *n
  values:
    podLabels:
      egress.home.arpa/apiserver: allow
