---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-pdf.${EXTERNAL_DOMAIN}
  namespace: s-pdf
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  secretName: tls-cert-pdf.${EXTERNAL_DOMAIN}
  issuerRef:
    name: letsencrypt-prod-${EXTERNAL_DOMAIN}
    kind: ClusterIssuer
  dnsNames: ['pdf.${EXTERNAL_DOMAIN}']
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: &n s-pdf
  namespace: *n
spec:
  routes:
    - match: Host(`pdf.${EXTERNAL_DOMAIN}`)
      kind: Rule
      services:
        - name: *n
          port: 8080
      middlewares:
        - name: compress
          namespace: ingress
  tls:
    secretName: tls-cert-pdf.${EXTERNAL_DOMAIN}
    domains:
      - main: pdf.${EXTERNAL_DOMAIN}
