---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app metrics-server
  namespace: kube-system
spec:
  interval: 1h
  chart:
    spec:
      chart: *app
      version: 3.12.1
      sourceRef:
        kind: HelmRepository
        name: *app
  values:
    apiService:
      insecureSkipTLSVerify: true
    args:
      - --kubelet-insecure-tls
