---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n victoria-metrics-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: *n
      version: 0.32.2
      sourceRef:
        kind: HelmRepository
        name: *n
  values:
    podLabels:
      egress.home.arpa/apiserver: allow
      ingress.home.arpa/remote-node: allow
    admissionWebhooks:
      enabled: true
      certManager:
        enabled: true
