---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-vw.${EXTERNAL_DOMAIN}
  namespace: vaultwarden
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  secretName: tls-cert-vw.${EXTERNAL_DOMAIN}
  issuerRef:
    name: letsencrypt-prod-${EXTERNAL_DOMAIN}
    kind: ClusterIssuer
  dnsNames: ['vw.${EXTERNAL_DOMAIN}']
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: &n vaultwarden
  namespace: *n
spec:
  routes:
    - match: Host(`vw.${EXTERNAL_DOMAIN}`)
      kind: Rule
      services:
        - name: *n
          port: 80
      middlewares:
        - name: compress
          namespace: ingress
        - name: authelia-authz
          namespace: authelia
  tls:
    secretName: tls-cert-vw.${EXTERNAL_DOMAIN}
    domains:
      - main: vw.${EXTERNAL_DOMAIN}
