---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-graf.${EXTERNAL_DOMAIN}
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  secretName: tls-cert-graf.${EXTERNAL_DOMAIN}
  issuerRef:
    name: letsencrypt-prod-${EXTERNAL_DOMAIN}
    kind: ClusterIssuer
  dnsNames: ['graf.${EXTERNAL_DOMAIN}']
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  routes:
    - match: Host(`graf.${EXTERNAL_DOMAIN}`)
      kind: Rule
      services:
        - name: grafana-main-service
          port: 3000
      middlewares:
        - name: compress
          namespace: ingress
  tls:
    secretName: tls-cert-graf.${EXTERNAL_DOMAIN}
    domains:
      - main: graf.${EXTERNAL_DOMAIN}
