---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: grafana
spec:
  routes:
    - match: Host(`graf.${DOMAIN_PUBLIC}`)
      kind: Rule
      services:
        - name: grafana-main-service
          port: 3000
  tls:
    domains:
      - main: graf.${DOMAIN_PUBLIC}
