---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-oidc-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: authelia/authelia-oidc-secrets
---
apiVersion: v1
kind: Secret
metadata:
  name: grafana-secrets
stringData:
  EXTERNAL_DOMAIN: ${EXTERNAL_DOMAIN}
