---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n kyverno
spec:
  chart:
    spec:
      chart: *n
      version: 3.2.5
      sourceRef:
        name: *n
        kind: HelmRepository
  values:
    crds:
      install: false
    customLabels:
      # netpols
      ingress.home.arpa/host: allow
      ingress.home.arpa/apiserver: allow
      egress.home.arpa/apiserver: allow
    backgroundController:
      rbac:
        clusterRole:
          extraResources:
            - apiGroups: ['']
              resources: [pods]
              verbs: [create, update, patch, delete, get, list]
            - apiGroups: ['*']
              resources: ['*']
              verbs: ['*']
    admissionController:
      replicas: 1
      rbac:
        clusterRole:
          extraResources:
            - apiGroups: ['']
              resources: [pods]
              verbs: [create, update, delete]
            - apiGroups: ['*']
              resources: ['*']
              verbs: ['*']
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app.kubernetes.io/instance: *n
              app.kubernetes.io/component: *n
