---
metadata:
  name: barman-secrets
  namespace: matrix
stringData:
  BARMAN_B2_BUCKET_NAME: ENC[AES256_GCM,data:mZz+ER2kX/UwJRydatKL79kSeFAwhWAH,iv:hWRT4evFmsPnM3KHBSm4hSUT94WybvRN2lgW+gfQfVU=,tag:kyGG0OJwiPpWJRrsXYwe/g==,type:str]
  BARMAN_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:z62867R08eq/DL6VRKRt7qpS/leiJkjZjgI=,iv:eMAsD3thV7yYhTYvH3cJIzQkCxnYFZQOEaciCQ7x+0k=,tag:f5E0JR5fXN25zKskNa8rgg==,type:str]
  BARMAN_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:Yl2oDwKrp2afi+q9Jvc2kZyKYmGrWqwcTK53W+Yl,iv:/wtFWtqs0LOweZqHqMlowm92XhTj6r4yA9WJgAHlukA=,tag:U3hRUe7os8puQvdo6Fm50Q==,type:str]
apiVersion: v1
kind: Secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RXpqM0JwT0FTclgwb3Jv
        eTcxcWs3RWpPdjRhUXdVSmdMaW0wV0s0VTB3Ci90SzZtVU9sVVdYQzg2dXFxaEdP
        cGVCZzZac1lmNUJEazRNcmRuTm5maU0KLS0tIGRNa09Va2VSS01SRTBZUTlmVjBv
        VHVEbTVIaVA1U1dHVDA5cmtBYmRLTHMKw2DxQrLoJZy5RN6li5OHt+YUQ5MQ5a5B
        8yCrTuBVZrUEhqTo8sG5fSIqF5SJORda86Z6T5ZLVEf8jVMo+kHWHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-28T16:22:59Z'
  mac: ENC[AES256_GCM,data:x0OB0lomdGf9gNBpICbsUuImCOqbHD6YDfK5LXrwFBxVu4ZIqG49PBTtSs4EX8dC0FZDiYLe2SZ28vuELN9olTkUTNhQocTmehLoITysRu30HwoUdKzSoVZg9dEzsn/6Q+vO3HnQh6TW2b97lE5aKyu0++9NFPHZtQ0OJUetedQ=,iv:kKqHCgcG9IsZEPisj+42KQLUxJTRCUtSlhvOBUQXDjE=,tag:wwaakhQ3BIahVxa4r+mYvw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
---
metadata:
  name: synapse-secrets
  namespace: matrix
stringData:
  DOMAIN_PUBLIC: ENC[AES256_GCM,data:Nn7RpJKvutQLXz/TxvvNHQ==,iv:I5wzME8c/5+ALr8zKavO6DsElot2Cg3A0/hIwaAdYnU=,tag:/KKTctPR+3qxJjhPZT47zw==,type:str]
  IP_PUBLIC: ENC[AES256_GCM,data:2hFxM7c96iq9G9w6,iv:UC2kkr/O6HshOWhTQWYzsJmexOjlk2yjVwk0ilE4DuA=,tag:NM5u4GBVnMO7viicYVglqA==,type:str]
  SYNAPSE_RECAPTCHA_KEY_PUB: ENC[AES256_GCM,data:APWn2xC3wBgc7Xo3MvyAoZTAe/eE4vfHtMNPo08l+Ka5NeWJVsrbkg==,iv:bD5qcxsfVoZZlkvV6X7pR5N3zS8S/FRIlUMqi2dDN5k=,tag:ylWKJYVfHjgtqYR2Vaz91A==,type:str]
  SYNAPSE_RECAPTCHA_KEY_PRIV: ENC[AES256_GCM,data:7AcMGt8LjpSTXJYKMPdvH0DVLVL2yI6NNjMFglza5z5OynYAdAi+sQ==,iv:KGh/o7IwtlTlXQkFfikfBlv5Qf2NYv1ZBTC4/9uNlKg=,tag:MpzFnE3zj0Pj9+0jLo/sdQ==,type:str]
  SYNAPSE_MACAROON_SECRET: ENC[AES256_GCM,data:+u4NpJdncAOVpYwLqkoXjv7YYo2TtAAif65pQhmnV+5oxm0Brm1kLRm8NbH+TZ+VE1aRXPgOeYtPMxWtnohG,iv:bBXsEi3VFd/ONC6vY41pKHUs5CqaDIvJG4ZQujscbMw=,tag:xdOBl1wRiewSDXYautt+LQ==,type:str]
  SYNAPSE_TURN_SECRET: ENC[AES256_GCM,data:/6E+1BdohRI1m02mGwLviM9Qg0rsF7sTXAoA3eaFJ01u08W1YAqrDNeNIn/U3YkI4APtORXKT0LW8f1MCb3X,iv:JKoW/HZJAvP1oS6AVM1t/rt4H6yhO6jSyyp0sNhiCgw=,tag:ERx0/7HH0p1+CdPektChaQ==,type:str]
apiVersion: v1
kind: Secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RXpqM0JwT0FTclgwb3Jv
        eTcxcWs3RWpPdjRhUXdVSmdMaW0wV0s0VTB3Ci90SzZtVU9sVVdYQzg2dXFxaEdP
        cGVCZzZac1lmNUJEazRNcmRuTm5maU0KLS0tIGRNa09Va2VSS01SRTBZUTlmVjBv
        VHVEbTVIaVA1U1dHVDA5cmtBYmRLTHMKw2DxQrLoJZy5RN6li5OHt+YUQ5MQ5a5B
        8yCrTuBVZrUEhqTo8sG5fSIqF5SJORda86Z6T5ZLVEf8jVMo+kHWHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-28T16:22:59Z'
  mac: ENC[AES256_GCM,data:x0OB0lomdGf9gNBpICbsUuImCOqbHD6YDfK5LXrwFBxVu4ZIqG49PBTtSs4EX8dC0FZDiYLe2SZ28vuELN9olTkUTNhQocTmehLoITysRu30HwoUdKzSoVZg9dEzsn/6Q+vO3HnQh6TW2b97lE5aKyu0++9NFPHZtQ0OJUetedQ=,iv:kKqHCgcG9IsZEPisj+42KQLUxJTRCUtSlhvOBUQXDjE=,tag:wwaakhQ3BIahVxa4r+mYvw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
---
metadata:
  name: jitsi-secrets
  namespace: matrix
stringData:
  JITSI_JICOFO_PASSWORD: ENC[AES256_GCM,data:yulATyMXBRNofLAWzSX1fRYo2PGcVTnHZHPGazcuNbCfIF0ILZNQHFfJfu11dllutGwZlIiDWAOzUH0ovyKw,iv:DE0noriD1DAP82n5SMXprHwZVJWEm/z5IPAJnFbD/Q0=,tag:m4rFmVLFmQrX0PjgvgcUtg==,type:str]
  JITSI_JICOFO_COMPONENT_SECRET: ENC[AES256_GCM,data:mco6t1imfGtHLx1hbUNP3hUAeYKZqikn4HWTLI0tUQ6y/5EnTaqC9yfmDIpU32r3FBHQs+3LueLu3VYS+/V5,iv:icBM60MpTs2niATxuoZnbXq2ojyEbehblLWfpjtJ488=,tag:Q5Gb87Ca49TZ3zFKd68gfQ==,type:str]
apiVersion: v1
kind: Secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RXpqM0JwT0FTclgwb3Jv
        eTcxcWs3RWpPdjRhUXdVSmdMaW0wV0s0VTB3Ci90SzZtVU9sVVdYQzg2dXFxaEdP
        cGVCZzZac1lmNUJEazRNcmRuTm5maU0KLS0tIGRNa09Va2VSS01SRTBZUTlmVjBv
        VHVEbTVIaVA1U1dHVDA5cmtBYmRLTHMKw2DxQrLoJZy5RN6li5OHt+YUQ5MQ5a5B
        8yCrTuBVZrUEhqTo8sG5fSIqF5SJORda86Z6T5ZLVEf8jVMo+kHWHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-28T16:22:59Z'
  mac: ENC[AES256_GCM,data:x0OB0lomdGf9gNBpICbsUuImCOqbHD6YDfK5LXrwFBxVu4ZIqG49PBTtSs4EX8dC0FZDiYLe2SZ28vuELN9olTkUTNhQocTmehLoITysRu30HwoUdKzSoVZg9dEzsn/6Q+vO3HnQh6TW2b97lE5aKyu0++9NFPHZtQ0OJUetedQ=,iv:kKqHCgcG9IsZEPisj+42KQLUxJTRCUtSlhvOBUQXDjE=,tag:wwaakhQ3BIahVxa4r+mYvw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
  name: synapse-oidc-secrets
  namespace: matrix
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: authelia/authelia-oidc-secrets
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RXpqM0JwT0FTclgwb3Jv
        eTcxcWs3RWpPdjRhUXdVSmdMaW0wV0s0VTB3Ci90SzZtVU9sVVdYQzg2dXFxaEdP
        cGVCZzZac1lmNUJEazRNcmRuTm5maU0KLS0tIGRNa09Va2VSS01SRTBZUTlmVjBv
        VHVEbTVIaVA1U1dHVDA5cmtBYmRLTHMKw2DxQrLoJZy5RN6li5OHt+YUQ5MQ5a5B
        8yCrTuBVZrUEhqTo8sG5fSIqF5SJORda86Z6T5ZLVEf8jVMo+kHWHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-28T16:22:59Z'
  mac: ENC[AES256_GCM,data:x0OB0lomdGf9gNBpICbsUuImCOqbHD6YDfK5LXrwFBxVu4ZIqG49PBTtSs4EX8dC0FZDiYLe2SZ28vuELN9olTkUTNhQocTmehLoITysRu30HwoUdKzSoVZg9dEzsn/6Q+vO3HnQh6TW2b97lE5aKyu0++9NFPHZtQ0OJUetedQ=,iv:kKqHCgcG9IsZEPisj+42KQLUxJTRCUtSlhvOBUQXDjE=,tag:wwaakhQ3BIahVxa4r+mYvw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
  name: synapse-db-root-credentials
  namespace: matrix
stringData:
  username: ENC[AES256_GCM,data:6TkHTEypfDQ=,iv:q1r3HRy8YvpWSDcxZ1mA+nNCsEeB78RjvnHL4kngKKk=,tag:nWIlNfzoaeHNqrPBhZRoiA==,type:str]
  password: ENC[AES256_GCM,data:+TMZrgZEKTPAT1jPBK9qYlZP8wRREJnZkuQLG36VQ39RzC7kkeydHXkcTnQPgOe8bSEQMba8srMdgAWRzSRC,iv:7lkTFOXn5HGtbNgWdcSPfuaJgy7ASSBcK6AZ5DF576I=,tag:2rZPHbs1OMafCDJjFKY1cQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RXpqM0JwT0FTclgwb3Jv
        eTcxcWs3RWpPdjRhUXdVSmdMaW0wV0s0VTB3Ci90SzZtVU9sVVdYQzg2dXFxaEdP
        cGVCZzZac1lmNUJEazRNcmRuTm5maU0KLS0tIGRNa09Va2VSS01SRTBZUTlmVjBv
        VHVEbTVIaVA1U1dHVDA5cmtBYmRLTHMKw2DxQrLoJZy5RN6li5OHt+YUQ5MQ5a5B
        8yCrTuBVZrUEhqTo8sG5fSIqF5SJORda86Z6T5ZLVEf8jVMo+kHWHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-28T16:22:59Z'
  mac: ENC[AES256_GCM,data:x0OB0lomdGf9gNBpICbsUuImCOqbHD6YDfK5LXrwFBxVu4ZIqG49PBTtSs4EX8dC0FZDiYLe2SZ28vuELN9olTkUTNhQocTmehLoITysRu30HwoUdKzSoVZg9dEzsn/6Q+vO3HnQh6TW2b97lE5aKyu0++9NFPHZtQ0OJUetedQ=,iv:kKqHCgcG9IsZEPisj+42KQLUxJTRCUtSlhvOBUQXDjE=,tag:wwaakhQ3BIahVxa4r+mYvw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
---
apiVersion: v1
kind: Secret
metadata:
  name: synapse-db-app-credentials
  namespace: matrix
stringData:
  username: ENC[AES256_GCM,data:6xsGC7m1iw==,iv:x/Tp9QXAfF1kXyF3ZJk1X3ONXN2+wgbr6FIWFoRAslo=,tag:KBtEtcdVyoVe6RWuFwMMrg==,type:str]
  password: ENC[AES256_GCM,data:hwOvufaidMeHad9oie6gjuzGiTKP0juDn/+ec6FR94vd5mdn4uavvQLTFB8DbFJEcxdlgRkFhKqZCF2GZSTx,iv:1OFGfv79icp8e/pqZsu4ctLGoYY6F5zAhLLQ6HhpyrA=,tag:TAWdBfjpzAoipwtvehy1eQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1RXpqM0JwT0FTclgwb3Jv
        eTcxcWs3RWpPdjRhUXdVSmdMaW0wV0s0VTB3Ci90SzZtVU9sVVdYQzg2dXFxaEdP
        cGVCZzZac1lmNUJEazRNcmRuTm5maU0KLS0tIGRNa09Va2VSS01SRTBZUTlmVjBv
        VHVEbTVIaVA1U1dHVDA5cmtBYmRLTHMKw2DxQrLoJZy5RN6li5OHt+YUQ5MQ5a5B
        8yCrTuBVZrUEhqTo8sG5fSIqF5SJORda86Z6T5ZLVEf8jVMo+kHWHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-28T16:22:59Z'
  mac: ENC[AES256_GCM,data:x0OB0lomdGf9gNBpICbsUuImCOqbHD6YDfK5LXrwFBxVu4ZIqG49PBTtSs4EX8dC0FZDiYLe2SZ28vuELN9olTkUTNhQocTmehLoITysRu30HwoUdKzSoVZg9dEzsn/6Q+vO3HnQh6TW2b97lE5aKyu0++9NFPHZtQ0OJUetedQ=,iv:kKqHCgcG9IsZEPisj+42KQLUxJTRCUtSlhvOBUQXDjE=,tag:wwaakhQ3BIahVxa4r+mYvw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
