---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n democratic-csi-deps
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/core/3-csi/democratic/deps/
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n democratic-csi-app
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/core/3-csi/democratic/app/
  interval: 1h
  prune: false
  wait: true
  dependsOn:
    - name: democratic-csi-deps
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: csi
  postBuild:
    substituteFrom:
      - kind: Secret
        name: democratic-csi-secrets
        optional: false
