---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources: [./hr.yaml]
configMapGenerator:
  - name: invidious-configuration
    files: [config.yaml]
generatorOptions:
  disableNameSuffixHash: true
