---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n coturn
spec:
  postRenderers:
    - kustomize:
        patches:
          - target:
              version: v1
              kind: Deployment
              name: *n
            # https://github.com/kubernetes-sigs/kustomize/issues/907# issuecomment-722913790
            patch: |
              - op: add
                path: /spec/template/metadata/labels/traefik.home.arpa~1ingress
                value: allow
  chart:
    spec:
      chart: coturn
      version: 0.8.6
      sourceRef:
        name: jaconi
        kind: HelmRepository
        namespace: flux-system
  values:
    extraOptions: ['--static-auth-secret=${SYNAPSE_TURN_SECRET}']
    realm: call.${EXTERNAL_DOMAIN}
    certificate:
      enabled: true
      dnsName: call.${EXTERNAL_DOMAIN}
      issuerName: letsencrypt-prod-${EXTERNAL_DOMAIN}
    traefik:
      enabled: false
    replicaCount: 2
    image:
      repository: coturn/coturn
      pullPolicy: Always
    resources:
      limits:
        cpu: 1000m
        memory: 500Mi
      requests:
        cpu: 100m
        memory: 50Mi
