---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-s3.${EXTERNAL_DOMAIN}
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  secretName: tls-cert-s3.${EXTERNAL_DOMAIN}
  issuerRef:
    name: letsencrypt-prod-${EXTERNAL_DOMAIN}
    kind: ClusterIssuer
  dnsNames: ['s3.${EXTERNAL_DOMAIN}']
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-api
spec:
  routes:
    - match: Host(`s3.${EXTERNAL_DOMAIN}`)
      kind: Rule
      services:
        - name: minio
          port: 9000
  tls:
    secretName: tls-cert-s3.${EXTERNAL_DOMAIN}
    domains:
      - main: s3.${EXTERNAL_DOMAIN}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-minio.${EXTERNAL_DOMAIN}
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  secretName: tls-cert-minio.${EXTERNAL_DOMAIN}
  issuerRef:
    name: letsencrypt-prod-${EXTERNAL_DOMAIN}
    kind: ClusterIssuer
  dnsNames: ['minio.${EXTERNAL_DOMAIN}']
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: minio-admin
spec:
  routes:
    - match: Host(`minio.${EXTERNAL_DOMAIN}`)
      kind: Rule
      services:
        - name: minio
          port: 9001
  tls:
    secretName: tls-cert-minio.${EXTERNAL_DOMAIN}
    domains:
      - main: minio.${EXTERNAL_DOMAIN}
