---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n traefik-certificates
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/core/5-ingress/traefik/certificates/
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: ingress
  postBuild:
    substituteFrom:
      - kind: Secret
        name: traefik-secrets
        optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n traefik-app
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/core/5-ingress/traefik/app/
  interval: 1h
  prune: false
  wait: true
  dependsOn:
    - name: traefik-certificates
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: ingress
  postBuild:
    substituteFrom:
      - kind: Secret
        name: traefik-secrets
        optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n traefik-middlewares
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/core/5-ingress/traefik/middlewares/
  interval: 1h
  prune: false
  wait: true
  dependsOn:
    - name: traefik-app
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: ingress
