---
stringData:
  TRAEFIK_LB_IP: ENC[AES256_GCM,data:cNnQ1OZDBCOI0oY=,iv:eBXnvINi7dNF4qu8ZPZpWFunG1s9GyFQaXvdjJ/XKZ0=,tag:/bdcpuik+4aB8SrUWoRM+Q==,type:str]
metadata:
  name: traefik-secrets
kind: Secret
apiVersion: v1
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGdVJsWGkwY1cxckQ0aVh6
        U1JVdGFmVnlOckY4VFcwekYrWmpDRFF5WVR3CngxcVNWMG00SnR3ZG5xeThRS2Zy
        RjZ2T0lyWHBoQzA4U0RYU3FONXBoWkkKLS0tIDNZUDJyMG1idXYwbzNxM0hGMXBY
        N0ZndXEwUk1DNytCcXJucUN1czc3eUEKtJFo0/SBOHlus4PwDMEWDB+1K0XYajOG
        iGAS7foJaXS27fW2Efi9ZG/fsK570knE31rhIZCZUx448F8yFrjAqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-30T00:34:51Z'
  mac: ENC[AES256_GCM,data:QB+njhx2384qk5j95hAtXJsDSyzBZPAU1RfxW0b/DunaA32StdfLwqHOZep4BWVKF1YW9wpSdaK85vMi4EOzoxKLAm7kiF/5FgCMVV7QapKpyZXOAZyLur8bgZ2IiVynDxOF6EP+DCtytmNb4Wh9Zyec971s/xFP5TWbzzijF+c=,iv:WHBX9L+kFQpC6SePzQHYLI27gjJSG6KOh2SGe7Mst4E=,tag:OL7ItWGUwkYZPAzgpHUJ7w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
