---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n kube-state-metrics
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/infra/monitoring/metrics-exporter/kube-state-metrics/
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: monitoring

---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n node-exporte
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/infra/monitoring/metrics-exporter/node-exporter/
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: monitoring
