---
apiVersion: grafana.integreatly.org/v1beta1
kind: GrafanaDatasource
metadata:
  name: victorialogs
spec:
  instanceSelector:
    matchLabels:
      instance: grafana-main
  datasource:
    name: VictoriaLogs
    type: victorialogs-datasource
    access: proxy
    url: http://vmlogs:9428
    jsonData:
      maxLines: '10000'
