---
apiVersion: v1
kind: Namespace
metadata:
  name: csi
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: latest
    kustomize.toolkit.fluxcd.io/prune: disabled
