---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n viewtube-db
  namespace: &ns viewtube
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/services/viewtube/db
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  targetNamespace: *ns
  commonMetadata:
    labels: *l
---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n viewtube-app
  namespace: &ns viewtube
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/services/viewtube/app
  interval: 1h
  prune: false
  dependsOn:
    - name: viewtube-db
    - name: 1-deploy-infra-storage-minio
      namespace: flux-system
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  targetNamespace: *ns
  commonMetadata:
    labels: *l
  postBuild:
    substituteFrom:
      - kind: Secret
        name: viewtube-secrets
        optional: false
