---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n k8up-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: k8up
      version: 4.7.0
      sourceRef:
        kind: HelmRepository
        name: *n
  values:
    k8up:
      skipWithoutAnnotation: true
