---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMServiceScrape
metadata:
  name: coredns
  namespace: kube-system
spec:
  jobLabel: jobLabel

  namespaceSelector:
    matchNames:
      - "kube-system"
  selector:
    matchLabels:
      k8s-app: kube-dns
      app.kubernetes.io/name: CoreDNS

  endpoints:
    - port: http-metrics
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
