---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./vmagent/
  - ./cadvisor.yaml
  - ./coredns.yaml
  - ./kubelet.yaml
  # - ./flux-system.yaml #TODO
  - ./cilium.yaml
  - ./kube-state-metrics.yaml
  - ./node-exporter.yaml
