---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./coredns.yaml
  - ./kube-apiserver.yaml
  - ./kubelet.yaml
  # - ./kube-controller-manager.yaml # It is mandatory for the kube-controller-manager to listen on 0.0.0.0
  # - ./kube-scheduler.yaml # Idem for kube-scheduler...
