---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n cnpg-operator
spec:
  interval: 1h
  chart:
    spec:
      chart: cloudnative-pg
      version: 0.21.2
      sourceRef:
        name: *n
        kind: HelmRepository
  values:
    podLabels:
      egress.home.arpa/apiserver: allow
      ingress.home.arpa/remote-node: allow
