---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
spec:
  chart:
    spec:
      chart: authelia
      version: 0.9.5
      sourceRef:
        name: authelia
        kind: HelmRepository
  values:
    image:
      registry: ghcr.io
      repository: authelia/authelia
      tag: ''
      pullPolicy: IfNotPresent
    rbac:
      enabled: true
      serviceAccountName: authelia
    service:
      type: ClusterIP
      port: 80
    ingress:
      enabled: false
    pod:
      kind: DaemonSet
      replicas: 1
      revisionHistoryLimit: 5
      strategy:
        type: RollingUpdate
      labels:
        traefik.home.arpa/ingress: allow
        smtp.egress.home.arpa/google: allow
        egress.home.arpa/ntp: allow
      env:
        - name: TZ
          value: Europe/Paris
      resources:
        limits:
          cpu: 1
          memory: 500Mi
        requests:
          cpu: 1m
          memory: 1Mi
      securityContext:
        container:
          runAsUser: 65534
          runAsGroup: 65534
          fsGroup: 65534
        pod:
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          privileged: false
      probes:
        method:
          httpGet:
            path: /api/health
            port: http
            scheme: HTTP
        liveness:
          initialDelaySeconds: 0
          periodSeconds: 30
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        readiness:
          initialDelaySeconds: 0
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 5
        startup:  # https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 6
    configMap:
      disabled: false
      key: configuration.yaml

      ### Common  ###
      server:
        port: 9091
        buffers:
          read: 4096
          write: 4096
        timeouts:
          read: 6 seconds
          write: 6 seconds
          idle: 30 seconds
          automatic_authz_implementations: [AuthRequest, ExtAuthz, ForwardAuth]

                                          # Important Note: If you configure the 'authz' section this is completely ignored.
      ntp:
        address: udp://${HOMELAB_GW_IP}:123
        version: 4
        max_desync: 3 seconds
      storage:
        encryption_key:
          disabled: false
          value: ${AUTHELIA_ENCRYPTION_KEY}
          path: storage.encryption.key
        postgres:
          enabled: true
          address: tcp://authelia-db-rw.authelia.svc.cluster.local:5432
          timeout: 5 seconds
          database: authelia
          username: authelia
          password:
            disabled: false
            value: ${AUTHELIA_PG_PASSWORD}
            path: storage.postgres.password.txt
      notifier:
        disable_startup_check: true #  Netpol is not instant.  # TODO ask for a configurable timeout duration or retry count
        smtp:
          enabled: true
          enabledSecret: false
          address: submission://${SMTP_HOST}:587
          timeout: 5 seconds
          sender: Authelia <authelia.${SMTP_MAIL}>
          subject: '[Authelia] {title}'
          startup_check_address: test@authelia.com
          username: ${SMTP_MAIL}
          password:
            disabled: false
            value: ${SMTP_PASSWORD}
            path: notifier.smtp.password.txt
          tls:
            server_name: ${SMTP_HOST}
            skip_verify: false
            minimum_version: TLS1.2
            maximum_version: TLS1.3
      log:
        level: info  # Level of verbosity for logs: info, debug, trace.
        format: json
      telemetry:
        metrics:
          enabled: true
          port: 9959
          buffers:
            read: 4096
            write: 4096
          timeouts:
            read: 6 seconds
            write: 6 seconds
            idle: 30 seconds
          serviceMonitor:
            enabled: true
      filters:
        disabled: false

      ### AUTHENTICATION  ###
      authentication_backend:
        refresh_interval: 5 minutes
        password_reset:
          disable: false
        ldap:
          enabled: true
          implementation: custom
          address: ldap://lldap-app-ldap.authelia.svc.cluster.local:3890
          start_tls: false
          timeout: 5 seconds
          base_dn: ${LLDAP_LDAP_BASE_DN}
          additional_users_dn: ou=people
          users_filter: (&({username_attribute}={input})(objectClass=person))
          additional_groups_dn: ou=groups
          groups_filter: (member={dn})
          user: uid=authelia,ou=people,${LLDAP_LDAP_BASE_DN}
          password:
            disabled: false
            value: ${AUTHELIA_LLDAP_PASSWORD}
            path: authentication.ldap.password.txt
          attributes:
            username: uid
            display_name: displayName
            mail: mail
            group_name: cn
      password_policy:
        standard:
          enabled: true
          min_length: 8
          max_length: 0
          require_uppercase: true
          require_lowercase: false
          require_number: true
          require_special: false

      ### SESSION  ###
      session:
        name: authelia_session
        same_site: lax  # https://www.authelia.com/configuration/session/introduction/#same_site
        expiration: 1 hour  # https://www.authelia.com/configuration/prologue/common/#duration-notation-format
        inactivity: 5 minutes
        remember_me: 1 month
        encryption_key:
          disabled: false
          value: ${AUTHELIA_ENCRYPTION_KEY}
          path: session.encryption.key
        cookies:
          - name: steropes_session
            domain: ${EXTERNAL_DOMAIN}
            subdomain: sso
            default_redirection_url: https://tools.${EXTERNAL_DOMAIN}
        redis:
          enabled: true
          enabledSecret: false
          host: authelia-redis-master.authelia.svc.cluster.local
          port: 6379
          password:
            disabled: false
            value: ${AUTHELIA_REDIS_PASSWORD}
            path: session.redis.password.txt

      ### 2FA  ###
      default_2fa_method: totp
      theme: light
      totp:
        disable: false
        issuer: Authelia
        skew: 1  # https://www.authelia.com/configuration/second-factor/time-based-one-time-password/#input-validation
        secret_size: 32
        algorithm: SHA1
        digits: 6  # https://www.authelia.com/configuration/second-factor/time-based-one-time-password/#digits
        period: 30
        allowed_algorithms: [SHA1]
        allowed_digits: [6]
        allowed_periods: [30]
      identity_validation:
        reset_password:
          jwt_lifespan: 5 minutes
          jwt_algorithm: HS256
          secret:
            disable: false
            value: ${AUTHELIA_JWT_SECRET}
            path: identity_validation.reset_password.jwt.hmac.key
        elevated_session:
          code_lifespan: 5 minutes
          elevation_lifespan: 10 minutes
          characters: 8
          require_second_factor: false
          skip_second_factor: false
      webauthn:
        disable: false
        timeout: 60 seconds
        display_name: Authelia
        attestation_conveyance_preference: indirect  # Options are none, indirect, direct.
        user_verification: preferred  # Options are required, preferred, discouraged.

      ### POLICY  ###
      regulation:
        max_retries: 3
        find_time: 2 minutes
        ban_time: 5 minutes
      access_control:
        secret:
          enabled: true
          key: configuration.acl.yaml
        default_policy: deny
        networks: []
        rules:
          - domain: flux.${EXTERNAL_DOMAIN}
            policy: two_factor
            subject:
              -   - group:admins
          - domain: vw.${EXTERNAL_DOMAIN}
            policy: two_factor
            resources: ^/admin(/.*)?$
            subject:
              -   - group:admins
          - domain: vw.${EXTERNAL_DOMAIN}
            policy: deny
            resources: ^/admin(/.*)?$
          - domain: vw.${EXTERNAL_DOMAIN}
            policy: bypass
            resources: ^/.*$
          - domain: yt.${EXTERNAL_DOMAIN}
            policy: two_factor
            resources: ^/admin(/.*)?$
            subject:
              -   - group:admins
          - domain: yt.${EXTERNAL_DOMAIN}
            policy: deny
            resources: ^/admin(/.*)?$
          - domain: yt.${EXTERNAL_DOMAIN}
            policy: bypass
            resources: ^/.*$
          - domain: kuma.${EXTERNAL_DOMAIN}
            policy: two_factor
            subject:
              -   - group:admins
          - domain: free.${EXTERNAL_DOMAIN}
            policy: two_factor
            subject:
              -   - group:admins
          - domain: nas.${EXTERNAL_DOMAIN}
            policy: two_factor
            subject:
              -   - group:admins
          - domain: eyes.${EXTERNAL_DOMAIN}
            policy: one_factor
            subject:
              -   - group:devs
          - domain: alert.${EXTERNAL_DOMAIN}
            policy: one_factor
            subject:
              -   - group:devs
          - domain: logs.${EXTERNAL_DOMAIN}
            policy: two_factor
            subject:
              -   - group:devs
          - domain: traefik.${EXTERNAL_DOMAIN}
            policy: one_factor
            subject:
              -   - group:devs
          - domain: test.${EXTERNAL_DOMAIN}
            policy: one_factor
            subject:
              -   - group:devs
          - domain: who.${EXTERNAL_DOMAIN}
            policy: one_factor
            subject:
              -   - group:randoms
          - domain: sync.${EXTERNAL_DOMAIN}
            policy: two_factor
            subject:
              -   - group:syncthing
      identity_providers:
        oidc:  # https://www.authelia.com/r/openid-connect/
          enabled: true
          enforce_pkce: public_clients_only
          minimum_parameter_entropy: 8
          enable_client_debug_messages: false
          hmac_secret:
            disabled: false
            value: ${AUTHELIA_HMAC_SECRET}
            path: identity_providers.oidc.hmac.key
          lifespans:
            access_token: 1 hour
            authorize_code: 1 minute
            id_token: 1 hour
            refresh_token: 1 hour and 30 minutes
          pushed_authorizations:
            enforce: false
            context_lifespan: 5 minutes
          jwks:
            - key_id: ''
              algorithm: RS256
              use: sig
              key:
                path: /secrets/authelia-oidc-jwks/oidc.jwks.RS256.pem
          clients:
            ### Grafana  ###
            - client_id: ${GRAFANA_OICD_CLIENT_ID}
              client_secret: ${GRAFANA_OICD_CLIENT_SECRET_HASH}
              client_name: Grafana
              public: false
              authorization_policy: one_factor
              require_pkce: true
              pkce_challenge_method: S256
              token_endpoint_auth_method: client_secret_basic
              userinfo_signed_response_alg: none
              redirect_uris: ['https://graf.${EXTERNAL_DOMAIN}/login/generic_oauth']
              scopes:
                - openid
                - profile
                - groups
                - email

            ### Minio  ###
            - client_id: ${MINIO_OICD_CLIENT_ID}
              client_secret: ${MINIO_OICD_CLIENT_SECRET_HASH}
              client_name: Minio
              public: false
              authorization_policy: two_factor
              userinfo_signed_response_alg: none
              redirect_uris: ['https://minio.${EXTERNAL_DOMAIN}/oauth_callback']
              scopes:
                - openid
                - profile
                - email
                - groups

            ### Outline  ###
            - client_id: ${OUTLINE_OICD_CLIENT_ID}
              client_secret: ${OUTLINE_OICD_CLIENT_SECRET_HASH}
              client_name: Outline
              public: false
              authorization_policy: one_factor
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_post
              redirect_uris: ['https://wiki.${EXTERNAL_DOMAIN}/auth/oidc.callback']
              scopes:
                - offline_access
                - openid
                - profile
                - email

            ### Vikunja  ###
            - client_id: ${VIKUNJA_OICD_CLIENT_ID}
              client_secret: ${VIKUNJA_OICD_CLIENT_SECRET_HASH}
              client_name: Vikunja
              public: false
              authorization_policy: one_factor
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_basic
              redirect_uris: ['https://do.${EXTERNAL_DOMAIN}/auth/openid/authelia']
              scopes:
                - openid
                - profile
                - email

            ### Memos  ###
            - client_id: ${MEMOS_OICD_CLIENT_ID}
              client_secret: ${MEMOS_OICD_CLIENT_SECRET_HASH}
              client_name: Memos
              public: false
              authorization_policy: one_factor
              userinfo_signed_response_alg: none
              token_endpoint_auth_method: client_secret_post
              redirect_uris: ['https://memos.${EXTERNAL_DOMAIN}/auth/callback']
              grant_types: [authorization_code]
              scopes: [openid, profile, email]

            ### Synapse  ###
            - client_id: ${SYNAPSE_OICD_CLIENT_ID}
              client_secret: ${SYNAPSE_OICD_CLIENT_SECRET_HASH}
              client_name: Synapse
              public: false
              authorization_policy: one_factor
              userinfo_signed_response_alg: none
              redirect_uris:
                - https://matrix.${EXTERNAL_DOMAIN}/_synapse/client/oidc/callback
              scopes: [openid, profile, email]
    secret:
      disabled: false
      mountPath: /secrets
      additionalSecrets:
        authelia-oidc-jwks:
          items:
            - key: oidc.jwks.RS256.pem
    persistence:
      enabled: false
