---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy  # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
metadata:
  name: allow-egress-to-sso
spec:
  endpointSelector:
    matchLabels:
      sso.home.arpa/egress: allow
  egress:
    - toFQDNs:
        - matchName: sso.${DOMAIN_PUBLIC}
