---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 0-deploy-core-0-deps
  namespace: &ns flux-system
  labels: &l
    kustomization.flux.home.arpa/name: deps
spec:
  path: ./kube/deploy/core/0-deps/crds/
  interval: 1h
  timeout: 10m0s
  prune: false
  wait: true
  sourceRef:  # ref ../../../flux/flux-repo.yaml
    kind: GitRepository
    name: *ns
  dependsOn: []
  commonMetadata:
    labels: *l
