---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n outline
  labels:
    helm.flux.home.arpa/app-template: true
spec:
  values:
    global:
      annotations:
        k8up.io/backup: 'true'
    controllers:
      outline:
        type: deployment
        replicas: 1
        strategy: Recreate
        pod:
          labels:
            traefik.home.arpa/ingress: allow
            sso.home.arpa/egress: allow
            egress.home.arpa/internet: allow
        containers:
          application:
            image:
              repository: outlinewiki/outline
              tag: latest
            resources:  # TODO refine
              limits:
                cpu: 1
                memory: 1Gi
              requests:
                cpu: 1m
                memory: 1Mi
            env:
              ### General settings  ###
              TZ: Europe/Paris
              DEFAULT_LANGUAGE: fr_FR
              URL: https://wiki.${DOMAIN_PUBLIC}
              NODE_ENV: production
              FORCE_HTTPS: false
              SECRET_KEY:
                secretKeyRef:
                  name: outline-secrets
                  key: OUTLINE_SECRET_KEY
              UTILS_SECRET:
                secretKeyRef:
                  name: outline-secrets
                  key: OUTLINE_UTILS_SECRET

              ### Storage settings  ###
              FILE_STORAGE: s3
              FILE_STORAGE_UPLOAD_MAX_SIZE: '26214400'

              ## S3 settings  ##
              AWS_S3_UPLOAD_MAX_SIZE: '26214400'
              AWS_REGION: us-east-1
              AWS_S3_UPLOAD_BUCKET_URL: https://s3.${DOMAIN_PUBLIC}
              AWS_S3_UPLOAD_BUCKET_NAME: steropes-outline
              AWS_ACCESS_KEY_ID:
                secretKeyRef:
                  name: outline-secrets
                  key: OUTLINE_S3_SECRET_ID
              AWS_SECRET_ACCESS_KEY:
                secretKeyRef:
                  name: outline-secrets
                  key: OUTLINE_S3_SECRET_KEY

              ## Databases settings  ##
              REDIS_URL: redis://outline-redis-master.outline.svc.cluster.local:6379
              DATABASE_URL:
                secretKeyRef:
                  name: outline-secrets
                  key: OUTLINE_DATABASE_URL

              ### OIDC settings  ###
              OIDC_AUTH_URI: https://sso.${DOMAIN_PUBLIC}/api/oidc/authorization
              OIDC_TOKEN_URI: https://sso.${DOMAIN_PUBLIC}/api/oidc/token
              OIDC_USERINFO_URI: https://sso.${DOMAIN_PUBLIC}/api/oidc/userinfo
              OIDC_USERNAME_CLAIM: preferred_username
              OIDC_DISPLAY_NAME: Authelia
              OIDC_SCOPES: openid offline_access profile email
              OIDC_CLIENT_ID:
                secretKeyRef:
                  name: outline-oidc-secrets
                  key: OUTLINE_OICD_CLIENT_ID
              OIDC_CLIENT_SECRET:
                secretKeyRef:
                  name: outline-oidc-secrets
                  key: OUTLINE_OICD_CLIENT_SECRET

              ### SMTP settings  ###
              SMTP_HOST: smtp.gmail.com
              SMTP_PORT: 587
              SMTP_SECURE: true
              SMTP_TLS_CIPHERS: TLSv1.2
              SMTP_USERNAME: &m
                secretKeyRef:
                  name: outline-secrets
                  key: SMTP_MAIL
              SMTP_PASSWORD:
                secretKeyRef:
                  name: outline-secrets
                  key: SMTP_PASSWORD
              SMTP_FROM_EMAIL: *m
              SMTP_REPLY_EMAIL: *m
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
        globalMounts:
          - path: /var/lib/outline/data
    service:
      http:
        controller: *n
        ports:
          http:
            port: 3000
