---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n cilium
  annotations:
    meta.helm.sh/release-name: *n
    meta.helm.sh/release-namespace: kube-system
  labels:
    helm.flux.home.arpa/crds-lifecycle: CreateReplace
    app.kubernetes.io/managed-by: Helm
spec:
  chart:
    spec:
      chart: *n
      version: 1.16.0-rc.1
      sourceRef:
        kind: HelmRepository
        name: *n
  values:
    prometheus: &prome
      enabled: true
      serviceMonitor:
        trustCRDsExist: true
        enabled: true
    k8sServiceHost: localhost
    k8sServicePort: 7445
    bpf:
      masquerade: true
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList: 10.66.0.0/16
        clusterPoolIPv4MaskSize: 22
    bgpControlPlane:
      enabled: true
    envoy:
      enabled: true
      prometheus: *prome
    encryption:
      enabled: true
      type: wireguard
      nodeEncryption: true
    kubeProxyReplacement: true
    localRedirectPolicy: true
    operator:
      prometheus: *prome
      replicas: 2
    hubble:
      relay:
        enabled: true
        prometheus: *prome
      ui:
        enabled: true
        rollOutPods: true
        podLabels:
          traefik.home.arpa/ingress: allow
      metrics:
        enableOpenMetrics: true
        enabled:
          - dns:query
          - drop
          - tcp
          - flow
          - port-distribution
          - icmp
          - http
    resources:  # for agent
      limits:
        memory: 1Gi
    socketLB:
      # -- Disable socket lb for non-root ns. This is used to enable Istio routing rules.
      hostNamespaceOnly: true
    cni:
      exclusive: false

    ### required for Talos  ###
    securityContext:
      capabilities:
        ciliumAgent:
          - CHOWN
          - KILL
          - NET_ADMIN
          - NET_RAW
          - IPC_LOCK
          - SYS_ADMIN
          - SYS_RESOURCE
          - DAC_OVERRIDE
          - FOWNER
          - SETGID
          - SETUID
        cleanCiliumState: [NET_ADMIN, SYS_ADMIN, SYS_RESOURCE]
    cgroup:
      autoMount:
        enabled: false
      hostRoot: /sys/fs/cgroup
    logOptions:
      format: json
