---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hubble
  labels:
    instance: vmsingle
spec:
  endpoints:
    - honorLabels: true
      interval: 10s
      path: /metrics
      port: hubble-metrics
      relabelings:
        - action: replace
          replacement: ${1}
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: node
  namespaceSelector:
    matchNames:
      - kube-system
  selector:
    matchLabels:
      k8s-app: hubble
  targetLabels:
    - k8s-app
