---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n vikunja
  labels:
    helm.flux.home.arpa/app-template: true
spec:
  values:
    global:
      annotations:
        k8up.io/backup: 'true'
    controllers:
      vikunja:
        type: deployment
        strategy: Recreate
        replicas: 1
        pod:
          labels:
            traefik.home.arpa/ingress: allow
            sso.home.arpa/egress: allow
            egress.home.arpa/gravatar: allow
        containers:
          application:
            image:
              repository: vikunja/vikunja
              tag: 0.24.2@sha256:c31c7d6cad49038ab8a7d1414845d4c45539b43dd6ddd082bcd148e6fcd7b01c
            resources:  # TODO refine
              limits:
                cpu: 1
                memory: 500Mi
              requests:
                cpu: 1m
                memory: 1Mi
            env:
              TZ: Europe/Paris
    persistence:
      data:
        type: persistentVolumeClaim
        accessMode: ReadWriteOnce
        size: 10Gi
        retain: true
        globalMounts:
          - path: /app/vikunja/files
      config:
        type: configMap
        name: vikunja-configuration
        globalMounts:
          - path: /app/vikunja/config.yml
            subPath: config.yml
            readOnly: true
    service:
      http:
        controller: *n
        ports:
          http:
            port: 3456
