---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./hr.yaml
  # - ./backup.yaml
configMapGenerator:
  - name: vikunja-configuration
    files:
      - config.yml
generatorOptions:
  disableNameSuffixHash: true
