---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n jitsi
spec:
  chart:
    spec:
      chart: jitsi-meet
      version: 1.4.1
      sourceRef:
        name: *n
        kind: HelmRepository
  values:
    nameOverride: *n
    enableAuth: false
    enableGuests: true
    publicURL: meet.${EXTERNAL_DOMAIN}
    tz: Europe/Paris
    image:
      pullPolicy: IfNotPresent
    web:
      replicaCount: 1
      image:
        repository: jitsi/web
      service:
        type: ClusterIP
        port: 80
      ingress:
        enabled: false
      podLabels:
        traefik.home.arpa/ingress: allow
        egress.home.arpa/internet-https: allow
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
    prosody:
      enabled: true
      useExternalProsody: false
    jvb:
      publicIPs: ['${IP_PUBLIC}']
      podLabels:
        ingress.home.arpa/world: allow
      service:  # TODO setup traefik tcp ingress
        type: LoadBalancer
