---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n jitsi
spec:
  chart:
    spec:
      chart: jitsi-meet
      version: 1.4.0
      sourceRef:
        name: *n
        kind: HelmRepository
  values:
    nameOverride: *n
    enableAuth: false
    enableGuests: true
    publicURL: meet.${DOMAIN_PUBLIC}
    tz: Europe/Paris
    image:
      pullPolicy: IfNotPresent
    web:
      replicaCount: 1
      image:
        repository: jitsi/web
      service:
        type: ClusterIP
        port: 80
      ingress:
        enabled: false
      podLabels:
        traefik.home.arpa/ingress: allow
        egress.home.arpa/internet-https: allow
      # podSecurityContext:
      #   fsGroup: 2000
      # securityContext:
      #   capabilities:
      #     drop: [ALL]
      #   readOnlyRootFilesystem: true
      #   runAsNonRoot: true
      #   runAsUser: 1000
      resources:
        limits:
          cpu: 1000m
          memory: 1024Mi
        requests:
          cpu: 100m
          memory: 128Mi
    xmpp:
      domain: meet.${DOMAIN_PUBLIC}  # TODO ?
    prosody:
      enabled: true
      useExternalProsody: false
    jvb:
      publicIPs: ['${IP_PUBLIC}', '${HOMELAB_GW_IP}']
      podLabels:
        ingress.home.arpa/world: allow
      service:  # TODO setup traefik tcp ingress
        type: LoadBalancer
    #   xmpp:
    #     user: jvb
    #     password: ${JITSI_XMPP_PASSWORD}
    # jicofo:
    #   xmpp:
    #     password: ${JITSI_XMPP_PASSWORD}
    #     componentSecret: ${JITSI_JICOFO_COMPONENT_SECRET}
