---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-meet.${EXTERNAL_DOMAIN}
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  secretName: tls-cert-meet.${EXTERNAL_DOMAIN}
  issuerRef:
    name: letsencrypt-prod-${EXTERNAL_DOMAIN}
    kind: ClusterIssuer
  dnsNames: ['meet.${EXTERNAL_DOMAIN}']
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: &n jitsi-web
spec:
  routes:
    - match: Host(`meet.${EXTERNAL_DOMAIN}`)
      kind: Rule
      services:
        - name: *n
          port: 80
  tls:
    secretName: tls-cert-meet.${EXTERNAL_DOMAIN}
    domains:
      - main: meet.${EXTERNAL_DOMAIN}
