---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n alloy
spec:
  chart:
    spec:
      chart: *n
      version: 0.4.0
      sourceRef:
        kind: HelmRepository
        name: grafana
  values:
    controller:
      podLabels:
        egress.home.arpa/apiserver: allow

    crds:
      create: false

    alloy:
      configMap:
        create: false
        name: grafana-alloy-config
        key: config.alloy

    stabilityLevel: "generally-available"

    mounts:
      varlog: true

    serviceMonitor:
      enabled: true
