---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
metadata:
  name: allow-egress-alloy-all
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: alloy
  egress:
    - toEndpoints:
        - {}
    - toEntities:
        - kube-apiserver

---
apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy # yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cilium.io/ciliumclusterwidenetworkpolicy_v2.json
metadata:
  name: allow-ingress-alloy-all
spec:
  endpointSelector: {}
  ingress:
    - fromEndpoints:
        - matchLabels:
            app.kubernetes.io/instance: alloy
