---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: &n lldap-app-http
spec:
  routes:
    - match: Host(`ldap.${DOMAIN_PUBLIC}`)
      kind: Rule
      services:
        - name: *n
          port: 17170
  tls:
    domains:
      - main: "ldap.${DOMAIN_PUBLIC}"
