---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: 0-deploy-core
  namespace: flux-system
  labels:
    kustomization.flux.home.arpa/core: "true"
    kustomization.flux.home.arpa/sops: "true"
spec:
  path: ./kube/deploy/core/
  interval: 5m0s
  timeout: 10m0s
  prune: false
  wait: false
  sourceRef: # ref ./flux-repo.yaml
    kind: GitRepository
    name: flux-system
  dependsOn: []
  commonMetadata:
    labels:
      kustomization.flux.home.arpa/core: "true"
  patches:
    # Make crds Kustomization a dependency of all child
    - patch: |
        - op: add
          path: /spec/dependsOn/-
          value:
            name: 0-deploy-core-0-deps
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/name notin (deps)

    # Make kube-system Kustomization a dependency of all child
    - patch: |
        - op: add
          path: /spec/dependsOn/-
          value:
            name: 0-deploy-core-1-kube-system
            namespace: flux-system
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/name notin (deps, kube-system)

    # Enable sops decryption for matching flux Kustomization child of this one
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          decryption:
            provider: sops
            secretRef:
              name: steropes-secrets-decrypt-sops-age
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/sops in (true)
        namespace: flux-system

    # Enable substitution for matching flux Kustomization child of this one
    - patch: |-
        apiVersion: kustomize.toolkit.fluxcd.io/v1
        kind: Kustomization
        metadata:
          name: not-used
        spec:
          postBuild:
            substituteFrom:
              - kind: ConfigMap
                name: steropes-vars
                optional: false
              - kind: Secret
                name: steropes-secrets
                optional: false
      target:
        group: kustomize.toolkit.fluxcd.io
        version: v1
        kind: Kustomization
        labelSelector: kustomization.flux.home.arpa/substitution in (true)
        namespace: flux-system
