---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./secrets-age.sops.yaml
  - ./secrets-ssh.sops.yaml
  - ../configs/
  - ./repos/
  - ./flux-install.yaml
  - ./flux-repo.yaml
  - ./0-core.yaml
  - ./1-infra.yaml
