---
apiVersion: v1
# yaml-language-server: $schema=https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/v1.30.0/secret.json
kind: Secret
metadata:
  name: steropes-secrets-decrypt-sops-age
  namespace: flux-system
stringData:
  age.agekey: ENC[AES256_GCM,data:vCmYpKlZiXTeBblnVu8eaVrRarcIy4C2aAaOJxGexpdPR0EbAXfhH1DNeUyM1WFjz4kqM1L/yuptFk/YEJaTCkTFrGLK8DpPkXLAXp3nVRDTiFeLsE149HvymV31mEKE0de2N4QvlMN7pPZYuQc5DZAz/FEc2feLG4ndphmIE5/7SnVO/uodrcJfHvCf5PjPywoD+/ZNS5SuI4Bumt5QQdlFDvj/IAmIjN9D7Lt3418YlZCRCD5pYFap8+v0,iv:A4EPCGwJjnxKIEW7ZdDhwqLNF1onJIMGBEswC6F9CuE=,tag:CjN/nl/Kd+kO3oEA5nx/xw==,type:str]
  sops.vault-token: ENC[AES256_GCM,data:q+t17tk2pwzUUTltYouuv6N+sZDolLvSeqYBrUkmsRZsoWypGcIpfdT6pHtR6mEnAT9bQpPU/4yItAZaac7Wxl3dBo2Oc3YyuAVxl4THfbeGxMczuYhP0MFBRWWrrAY=,iv:7rv508vgqPiYDNtgeznXzL5c3IN35cpGpDVqwkYDuSk=,tag:i+Fv/k/g3qT1CAMp4MkkRQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cWU5MHlld3NiL3M2SmlE
        QWZnSGxBVHEzblBFQUNVUDFnR0Y4QkZqMWtjCndSS0JCeENCSCt3QkV1Mkt0SS9W
        eVJNWEJVeHM5Y21CdzEzVmhMUEdkaW8KLS0tIDh5ditoZlM0U0tnMWVvRklFYWpW
        SEFDNFN4cFJUcHk4eXl2TWdJM3llNzgKSEPbiC0PFM4Kwa+4r/3F2+pO3ADCjNQp
        ncfjw11FgqdD4iBe+/wS127U2Hy9yroXW8jHEH+P6lJCzesFf3myCw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-22T14:44:08Z'
  mac: ENC[AES256_GCM,data:VeeP76sD3OL6uBYQZ3wPkRziR1qOy8U/jcngl3nukbDFba6abb1aRgUsuQfalkLmqt0jdr9hn/tlrfhyYCz9GzyGBbpR6f7zWW4kfLGo5FA5nB8aVOicPxci4C39VryOJFMm+U0WMbL1uB+uZV4+vI7x4xglNZ50bimBuaJiyUk=,iv:wLvXq9F0tp4q+Lidh6AZpMnqaVQxQ9c4Qw+fugzY/jk=,tag:i4x9qUK2YBfG1iRJBRp1tw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
