stringData:
  POD_NETWORK: ENC[AES256_GCM,data:kwT587Rr9hPQ,iv:q6UtVABgcDupTd9xpod5WDrHYXhidybUMxyNkP7zVXU=,tag:1POBFiX+npzXZU+eBQyfZw==,type:str]
  LB_NETWORK: ENC[AES256_GCM,data:zpnMkNO1yKJA,iv:O3HnDGxlKnTqhzkTzPFAF95417EZoiMg66BfUPRKlrc=,tag:9zdeQB22d98DjJWEPKo5ZQ==,type:str]
  GATEWAY_IP: ENC[AES256_GCM,data:CkmohAIiFDIYjuAPFA==,iv:XH4/Nad89+K7lV9Buf/No6kiatNDJjJIkwe88oUEfXs=,tag:4wtn1JI09ySbtVvSMkoqLA==,type:str]
  LAN_NETWORK: ENC[AES256_GCM,data:JQwkA4lbwhV38TA=,iv:qPKjAU6a0N6LX9flPbw57NfymQG6AXuh4mutvboINhI=,tag:qSYlUxE0FQRnp64M3aguVA==,type:str]
  PVE_IP: ENC[AES256_GCM,data:EYbS7g3EjEcUUUB/aw==,iv:cuu4MERFAPaiRZW0ZdwijseTKf/+38ZRtuvXFMIibHo=,tag:vuNp61PaBM05BhuQKfGJ2g==,type:str]
  TRUENAS_IP: ENC[AES256_GCM,data:ktvTPsO8/zVQMBMFcA==,iv:HweRWZ18avqGA2a1jHaETBkEvMUKEqzMNS9pwxoTOPU=,tag:97MlnI7vdVz8M5PnKsKmwg==,type:str]
  ISP_NETWORK: ENC[AES256_GCM,data:MSWNO/MvDeIQYsU=,iv:KFWLHpErQbyOLUSwUsT/p5x5nq6zerL1CxL00dMBxKQ=,tag:SzWJrPMKrUwfXyCdNH1ktQ==,type:str]
  ISP_ROUTER_IP: ENC[AES256_GCM,data:6OZyqDLfV5ATbb4wlw==,iv:VSlp0Yn6YtKGl7Iam8KeDqvYlWdK55RrQegURfHxb44=,tag:3+sHDpeizznwqt0bG64Jcg==,type:str]
metadata:
  name: cilium-secrets
kind: Secret
apiVersion: v1
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMMmp1ayt5WnludjF0RkpP
        Tk9mOEs4L3lUOFNWS0RtWEZZSDRqNGhnZjI0ClJlL0g5YmZRTHQwMU9BMHVrMEt1
        VlN4eHJPQm5hM0VyQXpMeGFxaDZObU0KLS0tIFZVNkRwendnUEJ4ek11T0U2MEJV
        WEdIM3pNRUFaY3NnZXU0SUg5ekZ4QzgKnbP0BYEj7ty2ZbXMT6WptMR9kpLQpfKK
        rK+5M+alK66ylT/Y5226Zqgacpw8xOOpu5n+CyrDfH2I+MM8OkuKCA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-23T12:55:28Z"
  mac: ENC[AES256_GCM,data:/t/Fwa8vVr3lbez6yHf73oOt4ayMT+V0/D9jHNc4Ht8h4MAALqng7fLo/Ms0q4SlSZHA5klw2CQUx8xqdADHwpHoGuBMOkExGb+DY/nGmm+lWtVczlFxh5LpE0KpDt5KXl1upWHs8oORwbHcN45f49wbqKckUG7YjQgco3OtIQY=,iv:k991FKFSvYCY3cyaT9jCMzEiwSpG/HKOTx+jHyGR6X4=,tag:hKgT2qc4hWsnW3dTKRUSIQ==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
