---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: &n syncthing-http
  namespace: syncthing
spec:
  routes:
    - match: Host(`sync.${DOMAIN_PUBLIC}`)
      kind: Rule
      services:
        - name: *n
          port: 8384
      middlewares:
        - name: compress
          namespace: ingress
        - name: authelia-authz
          namespace: authelia
  tls:
    domains:
      - main: sync.${DOMAIN_PUBLIC}
