---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n kube-state-metrics
spec:
  chart:
    spec:
      chart: *n
      version: 5.20.1
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    customLabels:
      egress.home.arpa/apiserver: allow
