---
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMAlert
metadata:
  name: main
spec:
  replicaCount: 1
  datasource:
    url: http://vmsingle-main.monitoring.svc:8429
  notifier:
    url: http://vmalertmanager-main.monitoring.svc:9093
  evaluationInterval: 30s
  selectAllByDefault: true
