---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tls-cert-sso.${EXTERNAL_DOMAIN}
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
spec:
  secretName: tls-cert-sso.${EXTERNAL_DOMAIN}
  issuerRef:
    name: letsencrypt-prod-${EXTERNAL_DOMAIN}
    kind: ClusterIssuer
  dnsNames: ['sso.${EXTERNAL_DOMAIN}']
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: &n authelia
spec:
  routes:
    - match: Host(`sso.${EXTERNAL_DOMAIN}`)
      kind: Rule
      services:
        - name: *n
          port: 80
  tls:
    secretName: tls-cert-sso.${EXTERNAL_DOMAIN}
    domains:
      - main: sso.${EXTERNAL_DOMAIN}
