---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n authelia-db
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/infra/authentification/authelia/db/
  interval: 1h
  prune: false
  wait: false
  healthChecks:
    - apiVersion: v1
      kind: Pod
      name: authelia-db-1
      namespace: &tns authelia
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: authelia-redis
      namespace: *tns
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: *tns
  postBuild:
    substituteFrom:
      - kind: Secret
        name: barman-secrets
        optional: false
---
apiVersion: kustomize.toolkit.fluxcd.io/v1  # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n authelia-app
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/infra/authentification/authelia/app/
  interval: 1h
  prune: false
  wait: true
  dependsOn:
    - name: authelia-db
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: authelia
  postBuild:
    substituteFrom:
      - kind: Secret
        name: authelia-secrets
        optional: false
      - kind: Secret
        name: lldap-secrets
        optional: false
      - kind: Secret
        name: authelia-oidc-secrets
        optional: false
