apiVersion: v1
kind: Secret
metadata:
  name: authelia-oidc-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring,outline,vikunja,memos
stringData:
  #ENC[AES256_GCM,data:B088iIAFAQniQkln3TI=,iv:2M/WvPH9jE5bMenZTxB//JLbkfvj2p0pRpz2DDavQ5Q=,tag:svUK58bHmbcr5BuhtXk2cQ==,type:comment]
  GRAFANA_OICD_CLIENT_ID: ENC[AES256_GCM,data:haWqUcrly2QSlhgVDheIrE0ypkRGrbpGMthBEwKf0D9do+SghBYX0e6Gq4fsa8F47SAI0yScYysej+HS7rMy4PjDGamPOvJ+,iv:jUpxQFLPIFbBrkS4kEiIsVMTP4bXni41Y5MtiVb5ok8=,tag:mO0R7lZWrSFgmoS8UKxS0Q==,type:str]
  GRAFANA_OICD_CLIENT_SECRET: ENC[AES256_GCM,data:Cfw6boU6aMWFLn+qn36C7og4w6Jv40W12MJx2vQ7lmBehUHQvACCiDPhyGxgAqa8oKdlEM1Zx035qOx+tCwRvQ==,iv:VcQoiVv49H7Toye2jj+9yNbXkM84JdIt8zoBHxulafY=,tag:JyJaUSXOu7Wejw6zd6pzIw==,type:str]
  GRAFANA_OICD_CLIENT_SECRET_HASH: ENC[AES256_GCM,data:KRCy48XEJuX51dRW66OwmZgdL7K+TqPa2xZ+z0A9/HffJFQq5Pv7GHw4qy0uWkOGPWXCD7OO+KB8LmUQelxfe2QzchHxYfii6vWXVtKE9jV5hJ0giJScmik7KCkNg8aXWbKoer7Gcw9Lwqraa7ZzMHdXpwTDoA==,iv:/ZGFCHatr/0pcXrlasIQnH/vRQ3SYopyGCqNV4Y3Trw=,tag:jJZi/mnSjhPQ9o3BSbTNVw==,type:str]
  #ENC[AES256_GCM,data:z2KSNU3yMgELKWhA,iv:LjuZnWcr5ohcDA3ZOWHsPMr02BHCeWRohW8aXm/txUI=,tag:KUCuy3G5eq6QFE8VoKBNrw==,type:comment]
  MINIO_OICD_CLIENT_ID: ENC[AES256_GCM,data:jEX96QBsKv0pfvyemn+DbJ5WcgQQghKW2aWj0yMf+E2m2kKG1f3oqbN1hRljj2M+9qCRBtMlVju7c2qXJtNHYo2w,iv:3R0pYgpy8x3SXdc57JONeEt2ykCs/H4r3cKQ8kT7xpE=,tag:Y5zdM/j/lVeGOVC7peDQmA==,type:str]
  MINIO_OICD_CLIENT_SECRET: ENC[AES256_GCM,data:aySm/G48oKzUI9iFs0mHQakmu+/chSEEZ/m/CePB9eBsTCKRYyisFqcGhja9jeo4lgqKDFWoDkXfjDViETo4Ng==,iv:g3zbblhQtf9hGK9jOwED4dc6Hqq762bPbaIfS9LMRSo=,tag:+07FnsEKz7Um4xOCuAw/8Q==,type:str]
  MINIO_OICD_CLIENT_SECRET_HASH: ENC[AES256_GCM,data:i1hzUwV2CTs4OMOtVYh5wDpUPydP4+QL3Cg5jLkd0v2eisrqZvDZ/fjkzb9jQDFuxjlEfkkG+/kNcd4aBmS3v3ome3Ag1moSinGULs0XiSOGX4bGO0bMUKV4vUd+tqUbdeqaXJnliW1bOkSIxAM2LfHXjvgHpA==,iv:mpiQzkOtUBNr6wzTBE2xrLpXapbNT37nuYCIuQBLxqM=,tag:p3eAnDuz62t1bAtY9JM7EA==,type:str]
  #ENC[AES256_GCM,data:bK0ubk+tGTJFEk7awxE=,iv:1EfZ59k/gEoJv6wzBm1Jblb227kwFn4qqDyAbMMA4Ao=,tag:0evx/LSc5t421dVdqJf3kQ==,type:comment]
  OUTLINE_OICD_CLIENT_ID: ENC[AES256_GCM,data:QISvARDVpCSx9zWR1Wke366nqSpgunp81bEtyRlCGs/qlb8FWu3QyRZq501dKupJ80wi8KVvkrECTerENPu5JFUp9+dMEFks,iv:o8qDHyfq57JiVxwngON+y5y9UWMaX/Ba8WpgKsb60hA=,tag:rDAuDLwSR5zW3+Ha8hMVvw==,type:str]
  OUTLINE_OICD_CLIENT_SECRET: ENC[AES256_GCM,data:vUMQTkxaIbEa+azL6rQyBPjHSp9kn/TYhGCkfsErn+zSPq4HvyhLUWH3hGHQxgG4ffnKE+HxkUju2XT1iw3nsA==,iv:Op2Q4atwGRE41LTmYKspqzEZ1XqFxP15fB7KQl7dh5E=,tag:443YSAr3/UCAd2zIuygJ6Q==,type:str]
  OUTLINE_OICD_CLIENT_SECRET_HASH: ENC[AES256_GCM,data:BPKSFaG8/xLNNPy3VEne40a4mHP2vfbz9ppOXHyJfmsJV6JCnKfed8RsJMRcMDCChOF3+dJT/XXOp4wbHvq+FpyYmHk0Pf7gB1CYFbsZ5ljIVaY+3CexM/3hxp5b02CnhFm4LY9IS8q9bwn1tpOSVRZtnvHtqQ==,iv:rjYrLg6UFksREImC5V3s2umCnJ9pVr9COnjnn8a1zEw=,tag:HynqFrYiwwjLwp1YARjdUg==,type:str]
  #ENC[AES256_GCM,data:v4D7xtumRif/khIkUyQ=,iv:IWEkgNqm6lGpAmnqFOwnSm49OzUfYRvaaQcYhfiyzXs=,tag:sqAsz9++0mYgWrPBL7T6Zw==,type:comment]
  VIKUNJA_OICD_CLIENT_ID: ENC[AES256_GCM,data:3OvWbYX8ckwx8DSsDin7U2TpCvBxk5NAeenc7XyfhK0xdKRsHrjUEZ/onIhahIRv1O4V2HSNMJl/EBGJPyytRKyw47xGkIr7,iv:u67uwG38lbRURvPw4Plwh7ivxZwetV8sSLwDVPBRjwI=,tag:spsN3ANWTbsSqcj0cA8LjA==,type:str]
  VIKUNJA_OICD_CLIENT_SECRET: ENC[AES256_GCM,data:WvhpyicvrZgO+pQWQ9lwTtkzc7/B4AcAZjUMhAeguiYMf/f9xLBDRYBMPl1eU8Q1tmSYz72jBapvpbumgTOJ9g==,iv:DShZSz73HhRtmP/bOf905K4UXavGP9Oo89UYi0Oqpsw=,tag:DqWskYD5e1ma8ryluTKMcA==,type:str]
  VIKUNJA_OICD_CLIENT_SECRET_HASH: ENC[AES256_GCM,data:XTwdStDVdr7XNFMpjyz4nHXLvTwtCMAGzZ47odCtznW8Y62mRnJCF3laeikUdTuc7K8CUbe/iPvPdGgLpoixHhGQCEPrCp/eSzkPQg2NzUU/0F/efiFGjEnR1ePkFo9LjvXyVM/cUiAhTuvl1sDfH5fqxx3D1A==,iv:aVbKG+/vQLqNpZs1Ts9LHeSL6sJhpsWcuJ2xRMYoUdE=,tag:bouoZ3h6X6ElxqqBPCJGPw==,type:str]
  #ENC[AES256_GCM,data:i6YL6bNnTClkBNCT,iv:gNrvpdICh/YzCyylEe2SH2rOAOmwPYSKzCVYXEXDKtI=,tag:eUr+3WxlrL1p3IycPZ+Yeg==,type:comment]
  MEMOS_OICD_CLIENT_ID: ENC[AES256_GCM,data:YJPTN0HZ83/8HbVgKF0p8TuhFXlLi4eNYTC1wxFPUSPbbOXFTZBRFKZXaHVUaJLL7ZMla05b0Dg8O46f8fFXdHkQ7mbprw==,iv:MKYrcv+ZjViIXIKH8MSYvIDaSTIaH+qXFYc8PBKxfR4=,tag:xYDm8rA6llmQLxQeCqavSA==,type:str]
  MEMOS_OICD_CLIENT_SECRET: ENC[AES256_GCM,data:7vRX8uQM5ICiBjxzWGP4Mb4pWbYgNc5LOeQ8ngyBfrQYfiHK7rng+Ohh,iv:EnejfWF54gQrxACGR5hV5jKQLjepRluaUCaPa/KezeA=,tag:A3xLibCV8ywD/oSQmm1FjQ==,type:str]
  MEMOS_OICD_CLIENT_SECRET_HASH: ENC[AES256_GCM,data:Uv3QMDMZLnvcN6J0KNT6PWRNhG3bR02JO488zG7CwPd4sD0nyyq2BfAqGlosViiGYC0HKiW9UwEZuF60ox9199N3lsnHRg+Pyk+8FMwvUAOHms3Nfv5WW14HtnD5+FwuE7C9Q7h9xp+UlxhekLuhDXRxf0PYoQ==,iv:ytcZkwbCtCzF300qZtHzarP3hRmfufTAFcMjJ8DED/Y=,tag:OaW0/EASmthvph0tl8i1jw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4VlN1NFNmNWdnQWE3Nzc0
        UzhvUVRrcXVLQ1VrNEF4Y0xYYzc1SWpqNEVNCkhoVVlnU3ZOaG5LaHU2eG5iV1Y1
        WjY1YWZrMWRpM3ZiMld6UkZ6TTdXZWcKLS0tIGZsd1c0dW1uSTZHQWdvbnlTTTFm
        VEhJRW9NdGc4OHVnNDlNZ3N2YkorUzAKv6kMtTLJkeyxjkAqixyhQBmvU5/nZ/mV
        UdkCtiRujCm4JYmVr7XCHvG2dZNY6j3RzUrjw+boeSP/B17fRD5aYQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-30T12:24:26Z"
  mac: ENC[AES256_GCM,data:ziEK5BNjhkP9vk75dBXuMx3NbFNpYgGTKvhNeuDBrT3MB0hHXo2ipTVnOnYzgzsYB9ncV3SM0dFRNpXjKvqX3X20Sy4UjtydmnKiAq5g7pKvMhh9fAVYocUdoBTBcTEM6gnqz3x+6Xou47pTGBWGSPAbEoNjnuyRys9e049+ZWE=,iv:jojJGiZjVUkI2vmffBUr8YChQCPp3G8EFJtdGzRHCoQ=,tag:jOWx5TherdQhYVwqPo16Ug==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
