apiVersion: v1
kind: Secret
metadata:
  name: authelia-oidc-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
stringData:
  #ENC[AES256_GCM,data:Z71ZND1TB4KTktDt2qc=,iv:nVpPfLbOOCwW/by3wZWwRuozDyIzDnOml10maERvweE=,tag:PKg7r1cM2CWzWaBbVRh3yw==,type:comment]
  GRAFANA_OICD_CLIENT_ID: ENC[AES256_GCM,data:KE0pbYdb8ckXzFR9ukn89T0HDQzQ1xq/3bWRIGiNl+k1Z9ythw4fvoh6uQO/TB2jIlJREyxtYhfLzG/fqdy6GYrdP4XjfIMV,iv:Y38S/cIssbhbbInX4Du0x9rijYLf7r89m9PMSw/2Okw=,tag:Fa6BQknPZY5P+ns4SbnvSQ==,type:str]
  GRAFANA_OICD_CLIENT_SECRET: ENC[AES256_GCM,data:Qcb9HcicEGC1Nf3UpkW+VYrDY4ACfK97j/4qkv52lI5wVRsFNA9FW82bzbi+HTod+E/pxwwTohlX9+U+y/kAdQ==,iv:6u/xrNm2DbhE4OiUkLfyIerL4ZNVx0tkREuYA/DcjYk=,tag:TxKWVWeqnxp0nNe9pUjxEQ==,type:str]
  GRAFANA_OICD_CLIENT_SECRET_HASH: ENC[AES256_GCM,data:Px3i7u9xtydqbL921StJgV+TXvRtivDRztQzdux1SW3ZUkkivmHqUjYnK80h9qaMYskQJ5x/iUkQOFcHX1UXiGemBi3KvA73+qZ6uY5bCtgHpoFaaZ5lkX5yXS9++p60T9v2wQrAR7gnFxbl7fdHsCylAB15ew==,iv:CAU01Tj7PAVbt4kJ+Qjk/Ro6lp/q8LWjHa99VTn7F+I=,tag:A9r/ZlLmB8N9/eJWOu1iJg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBORTFlRElXMkllUTBuNGdQ
        WXBnOWVGMzNicVlwaXVwK2wzZTdWRVpqQ25zCkwrS09lUWFJOG5acXRVcmZEWXRT
        RzdRc3ZsSi9TZ1BqeXhjNUx3bEVMd2sKLS0tIEEySmxqa0x3R2tDZFlnUlJVUGZj
        MklXNUgyKzZLN1VjRmNmZjZsUzNTUW8KutAzOUqK+XptQOs1bm2XtK5hWqjoubnJ
        jQkv31AdXv1Sg45FAH5N31lx5CiZupi+E8uua7IawYTmrfyAWVHX3w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-25T21:05:27Z"
  mac: ENC[AES256_GCM,data:2uthlVgB1IWcBcfJQCylm+zjcg37CxcXF+nfwwweedfrExpcwaIMaAeI0VF25PbgIOPr3Ww+dlXBNyeRz6yXFaBJdU/RtvB0zAj3+0OTQSBSSBeDBjhFZwciQe12KrHzMmxTCK83IYOydtpt3wgU59ikrkdK17msCzhMe3en9DQ=,iv:0MqPH5Ps027j0b6ENsw6ZBS/Wo3y1tINlG0gadcc9Ow=,tag:2aJamS66+eaJT8ZC3XRXrA==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
