apiVersion: v1
kind: Secret
metadata:
  name: authelia-oidc-secrets
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: monitoring
stringData:
  #ENC[AES256_GCM,data:w7SrTaro9eupK1DTvqM=,iv:yk+e3irpzoop/cVbRt0T0e8lDfm31JTQikr3V0ld0Ms=,tag:dIHKouu7trXIcfKNOQd1rw==,type:comment]
  GRAFANA_OICD_CLIENT_ID: ENC[AES256_GCM,data:Boy2roafN3NRT7I0Jf0qJsManujZrxn7eTtl3HO8IKTEoTBL8EO8WdXzsmyGasKeNuCnIpVYd0SaQx5vdJf0oKaWsZnJsRHg,iv:ni74XloJ5TSXlOyfiAgn54AeUdoj8DzOdJhnYp+kbCk=,tag:SQ501neO9Dob8Tl4E2np7Q==,type:str]
  GRAFANA_OICD_CLIENT_SECRET: ENC[AES256_GCM,data:mFtriK2JnZVkQH6Ej06dkW4505m3JmnFrIPvgMVQvYw+3NiuFT+Xz/4uKI8+Cz0yQg7RtnppEOC2wKRCwCGBDQ==,iv:IcXqN/+cJUpsa0YoCSjFJjVyxLEMd+cnBtnWNiIlNDA=,tag:w5DmwUupMJ97dfxjhsYlew==,type:str]
  GRAFANA_OICD_CLIENT_SECRET_HASH: ENC[AES256_GCM,data:xdBRKK7mQ4vmqeqeLRbKmO6FORnUXajJdNCbYAFS8X7h/6LZpd4TcJ3jZlDs7mC/ybTiwnjvqLNjPe1BrO2A8bM+0WTvHdjYxY4pVrFXVgTLxB1iJKKI7yRLdqTOlz4vkc5jpfZnJaKLzpUM5nF3vEOthNfFWg==,iv:F0IRmL/tQSWOLIDGTchJkWV1OPUp/r5+GPGLqicmqlg=,tag:5q0sEob8LPUuFGdxl95R5Q==,type:str]
  #ENC[AES256_GCM,data:h2uO31Fnkr+XNiZF,iv:NIx3837EBP6SQZBv+K4/3nBIdn2qzG4hdw7SR3n/0g4=,tag:s/HOSccj4yUqqTbhDfAfYA==,type:comment]
  MINIO_OICD_CLIENT_ID: ENC[AES256_GCM,data:rgLvXSeCKfj/NS/WZDPS72/YnnQJxCqluiiQpdIlvZZoZdw1gyFGq8FIAdW32TwkaC+l6Z2BbbCBc8hidHPgoWxi,iv:xHEeg9/O+gLJE2L4Nqvv2MN0nebNfV/ngSD7D0HYI7I=,tag:wWLi8Nqe2OFjdaA5tV5R/A==,type:str]
  MINIO_OICD_CLIENT_SECRET: ENC[AES256_GCM,data:Em1lu51lcvEXqUXGQoX/frUdJSHKCwvpEYHH5xr1CbfftLxyG4i0tFZIUUQ7xA5LJePp+Uk2yONzQKt21oUG0w==,iv:7wujY8MkOgPhqTlIcUwX2jWw9dc8KAWgh705ymedZ3U=,tag:1JMALpkMw3LFKOeRDV5ATw==,type:str]
  MINIO_OICD_CLIENT_SECRET_HASH: ENC[AES256_GCM,data:GdcDHYV7J/sTgxDR1CkLrCXgkQxF2hLXs8Dd6gCUwiGLBDktab4ekBSV6gjeCJQ2SB0P0Dc1NV44ceMVAy/ftwXULrwoWUwd7rn1O68VO/2UkRTwp6T4dcDue2WEmOHWmrBTCqQLltIuRz+ZUeEZ0q+dZJ42DA==,iv:5SXVm1iSLmx9e802f7y9CEnY+bxq8LEagnK54KKQyeU=,tag:sRlHWsMBt6DiSlPy/MoWrA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnZFJDelU4cEs0bVl6cmts
        ZjE5aVlxT0ptem9DTGRkcFBnYXljUkZWZjBNCjdLTzI0MWhJc29mSkErZnJ0QXlP
        TnJld2t6d3VzY1BsbURyRlFKQ2duSEUKLS0tIEhpajdvdEp0aDdmVi9nb3krZmpW
        UWFoSWQydmMvZzRmTFg1N0dNbVZsaWMKcunOKUuJEflFEpTQW7XRLtM/0sQEj/I9
        iWh+2Alt/AdvmSVkaHFSU/E5Grb+R3uAyIThml/kgq2i6xoyYxIPGA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-27T18:24:18Z"
  mac: ENC[AES256_GCM,data:iwd18X/EEANZDaGGvyh7JfY++C4H+e9t9yyRtyfe/4ydpAPWEHzyQRtFXb5Sj8FNxsPjOGI5XDTISaYFV3ldJsvNEFqZrl/CZK+30M2jtgBzvDzUxyXXjRfQgXB1RMhE9OcrSr/xAPu/HfH/CaOg3UgnUh42VMXrn2UCgHYu/U8=,iv:/yi6srW7G8s/8oddIZKMXprc6zgH94x9/iE4kEmCtaE=,tag:CVTVyd4sRxXtQB9EK48Bag==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
