---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod-${EXTERNAL_DOMAIN}
spec:
  acme:
    email: ${ADMIN_EMAIL}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod-${EXTERNAL_DOMAIN}-private-key
    solvers:
      - selector:
          dnsZones: ['${EXTERNAL_DOMAIN}']
        dns01:
          cloudflare:
            email: ${ADMIN_EMAIL}
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token
