---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./0-deps/ # Deploy prometheus CRDs, needed for cilium deployment. May be used for others things in future
  - ./1-kube-system/
  - ./2-policy/
  - ./3-csi/
  - ./4-tls/
  - ./5-ingress/
  - ./6-operators/
