---
metadata:
  name: barman-secrets
  namespace: vikunja
stringData:
  BARMAN_B2_BUCKET_NAME: ENC[AES256_GCM,data:d2nnqVZOxy7FLcvhALiy8khDadyqAjOp,iv:3hPArIARZyZc9xIzkpS817+Z8nerMku2Vx+FyBEI618=,tag:G01d/vduQ/4wchVdOJDZbA==,type:str]
  BARMAN_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:OBVmzl6si1li1O2/lyvUJ6LO6Jjl/nsw4l8=,iv:7YzDt7uxVm6trgfP3oTIlR9N57nn76WF/Bv+VvHUVVA=,tag:bVfTLdvspEgRG6D0+WQ6DQ==,type:str]
  BARMAN_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:17RxBHeyntLGnrYtG7wChUNlyI1ytU+orKH1y+sq,iv:lzBpuIxrR6XRXPfWI/bfXxw3Qwzil0qgVd1HHeIG8+w=,tag:DLkSNAFvLjTmcEHC55UCKw==,type:str]
apiVersion: v1
kind: Secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Qy9WS0ZucUJuWDdMMEFa
        ZlZEUmptYzlCUXpoWHRQRVgrNklCZ0ZCSEN3CkRQaEEzS2tjOXVjVnJmVjJocVZQ
        SmNhS2xYVWlzQXVFNFJNamVHK1JSa0UKLS0tIFZCMDFsdUVoSzJMRi9HUWtKOG13
        cUt4WTZWVzgvcDBYbHgvRW16U0piRU0KMcNKoZLVeGNuYGaem2Zs4C15X/26sDkV
        pILZICZPZ1i+I+ZHpbETsM+s9CCE7o14KQ2sdQ+OxxJKIRPN5GbFNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-29T02:53:07Z'
  mac: ENC[AES256_GCM,data:d9vswB5y3V/yvYrtJOkH1nfC0k426toiga4tZkYXieyL92TFC/YgE0qlmxizj1//2VlHUGzD0RxdG83GY8pykzwDQhabAnT01fcmNpdnzk0sb63S4gPAahO1IGkDW8qMUG3VBQfO/tl/dPBuekv+zHKUVmvNX5uu39TQMDAx+bA=,iv:I6VHIthOwyc8k6NFJkCixRJkBG1V+n8OxpSE6p1E2xk=,tag:+INn2WwFrKZGY/I5mW8Hig==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
---
metadata:
  name: vikunja-secrets
  namespace: vikunja
stringData:
  DOMAIN_PUBLIC: ENC[AES256_GCM,data:1qRf9AaqiHXuaqYdMJwdIw==,iv:hrOB1TFL4z2TcV31yJ+CPWJBylVFjKeWcyYeqW6JXbo=,tag:CbNR0k3OAh+QrGhFvRzrNw==,type:str]
  VIKUNJA_SERVICE_JWTSECRET: ENC[AES256_GCM,data:yDlNrUw/Vs3BiNdey2nsEI3azAl4T4RhjafWswSNLqoLXHFePQKxIaT+p3grVOgt+tICCI8F9fIwlLMYdqTcBA==,iv:ddSqitKB9d+fKQcRGSX2ZWJr8wU5sj783+ktjZHgxxo=,tag:i1Al3UKI5qMSNB90gCy8BQ==,type:str]
  K8UP_B2_BUCKET_NAME: ENC[AES256_GCM,data:vE1HPX1FNq85Pz7TIjkJehyVRlE+aA==,iv:Hy5IOxx5i1kvg8CTAD6DwVf5He4BAoO6LX06Q5bJRvQ=,tag:TxJAao+6ibHqfJApfL3v0A==,type:str]
  K8UP_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:SvNq8LWyVYzta6+F1BBJuCkLXHrMFzW1,iv:67VAhDvDeC/7rCO7TDpIcVtFaoWiZNYDeMjNygpm2eU=,tag:BEaxY4K02Lw36nuqVUECpg==,type:str]
  K8UP_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:YVEmBved8UlNZLK/r9uBICNM+dKcqqa7IdlCUA==,iv:WUzwPn8qyDC/OmIRH52gFQm6uS61qdBUKO/Erph4Lbg=,tag:75eZtQF/8GGj2WKw75XLsw==,type:str]
  K8UP_RESTIC_KEY: ENC[AES256_GCM,data:1nnpHRgBhTgM/SwnO7X5HDBk,iv:ich1C47JBcs4ymRFDztujzUgX73kj5ZCm8DoRZdSFa4=,tag:BXFuVoNVpr6/l8nPl5u0eg==,type:str]
apiVersion: v1
kind: Secret
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Qy9WS0ZucUJuWDdMMEFa
        ZlZEUmptYzlCUXpoWHRQRVgrNklCZ0ZCSEN3CkRQaEEzS2tjOXVjVnJmVjJocVZQ
        SmNhS2xYVWlzQXVFNFJNamVHK1JSa0UKLS0tIFZCMDFsdUVoSzJMRi9HUWtKOG13
        cUt4WTZWVzgvcDBYbHgvRW16U0piRU0KMcNKoZLVeGNuYGaem2Zs4C15X/26sDkV
        pILZICZPZ1i+I+ZHpbETsM+s9CCE7o14KQ2sdQ+OxxJKIRPN5GbFNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-29T02:53:07Z'
  mac: ENC[AES256_GCM,data:d9vswB5y3V/yvYrtJOkH1nfC0k426toiga4tZkYXieyL92TFC/YgE0qlmxizj1//2VlHUGzD0RxdG83GY8pykzwDQhabAnT01fcmNpdnzk0sb63S4gPAahO1IGkDW8qMUG3VBQfO/tl/dPBuekv+zHKUVmvNX5uu39TQMDAx+bA=,iv:I6VHIthOwyc8k6NFJkCixRJkBG1V+n8OxpSE6p1E2xk=,tag:+INn2WwFrKZGY/I5mW8Hig==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
  name: vikunja-oidc-secrets
  namespace: vikunja
  annotations:
    reflector.v1.k8s.emberstack.com/reflects: authelia/authelia-oidc-secrets
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Qy9WS0ZucUJuWDdMMEFa
        ZlZEUmptYzlCUXpoWHRQRVgrNklCZ0ZCSEN3CkRQaEEzS2tjOXVjVnJmVjJocVZQ
        SmNhS2xYVWlzQXVFNFJNamVHK1JSa0UKLS0tIFZCMDFsdUVoSzJMRi9HUWtKOG13
        cUt4WTZWVzgvcDBYbHgvRW16U0piRU0KMcNKoZLVeGNuYGaem2Zs4C15X/26sDkV
        pILZICZPZ1i+I+ZHpbETsM+s9CCE7o14KQ2sdQ+OxxJKIRPN5GbFNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-29T02:53:07Z'
  mac: ENC[AES256_GCM,data:d9vswB5y3V/yvYrtJOkH1nfC0k426toiga4tZkYXieyL92TFC/YgE0qlmxizj1//2VlHUGzD0RxdG83GY8pykzwDQhabAnT01fcmNpdnzk0sb63S4gPAahO1IGkDW8qMUG3VBQfO/tl/dPBuekv+zHKUVmvNX5uu39TQMDAx+bA=,iv:I6VHIthOwyc8k6NFJkCixRJkBG1V+n8OxpSE6p1E2xk=,tag:+INn2WwFrKZGY/I5mW8Hig==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
---
apiVersion: v1
kind: Secret
metadata:
  name: vikunja-db-root-credentials
  namespace: vikunja
stringData:
  username: ENC[AES256_GCM,data:+7SPKVMtefo=,iv:kNBJ36NpA6+DhNSqITaVbcBx2swx4a2ksJKuiPY9GuA=,tag:borAxMcFT8OWrdhrb3hwYA==,type:str]
  password: ENC[AES256_GCM,data:mu26O09FVwN+lsZWm5ODJBziAJXMmUKR+H6YEdoW/c2OgVRrYkPb52l3vlaaSHS2oD6Ae1Q=,iv:Bo3iEwQdKdLt/Did6OqYC1GmFF0JPn6GvQMvt+rCQGw=,tag:WYjzQfplGBmk+AiBSXgXWQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Qy9WS0ZucUJuWDdMMEFa
        ZlZEUmptYzlCUXpoWHRQRVgrNklCZ0ZCSEN3CkRQaEEzS2tjOXVjVnJmVjJocVZQ
        SmNhS2xYVWlzQXVFNFJNamVHK1JSa0UKLS0tIFZCMDFsdUVoSzJMRi9HUWtKOG13
        cUt4WTZWVzgvcDBYbHgvRW16U0piRU0KMcNKoZLVeGNuYGaem2Zs4C15X/26sDkV
        pILZICZPZ1i+I+ZHpbETsM+s9CCE7o14KQ2sdQ+OxxJKIRPN5GbFNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-29T02:53:07Z'
  mac: ENC[AES256_GCM,data:d9vswB5y3V/yvYrtJOkH1nfC0k426toiga4tZkYXieyL92TFC/YgE0qlmxizj1//2VlHUGzD0RxdG83GY8pykzwDQhabAnT01fcmNpdnzk0sb63S4gPAahO1IGkDW8qMUG3VBQfO/tl/dPBuekv+zHKUVmvNX5uu39TQMDAx+bA=,iv:I6VHIthOwyc8k6NFJkCixRJkBG1V+n8OxpSE6p1E2xk=,tag:+INn2WwFrKZGY/I5mW8Hig==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
---
# Only needed for bootstraping
apiVersion: v1
kind: Secret
metadata:
  name: vikunja-db-app-credentials
  namespace: vikunja
stringData:
  username: ENC[AES256_GCM,data:FPXx2+KCww==,iv:NP1SCvmwq1rD5rNlV+7gPbRskYUlZAedDEBVGGdj7D8=,tag:jeXJNSLsmVWg+XC2WMmFoA==,type:str]
  password: ENC[AES256_GCM,data:9S1ammUtZ/vgMgsy8xUfPMcNoryUgwEGgODCjTo/5wwseshmxFKhIcHvVKe6oJYxSfcJ5qc=,iv:O2rCR62uoJYtrFcdW7zFqKLqcUebWTwAB2GyOSFCAXo=,tag:O5ASbQ2UnmYbrzJK/dApzw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Qy9WS0ZucUJuWDdMMEFa
        ZlZEUmptYzlCUXpoWHRQRVgrNklCZ0ZCSEN3CkRQaEEzS2tjOXVjVnJmVjJocVZQ
        SmNhS2xYVWlzQXVFNFJNamVHK1JSa0UKLS0tIFZCMDFsdUVoSzJMRi9HUWtKOG13
        cUt4WTZWVzgvcDBYbHgvRW16U0piRU0KMcNKoZLVeGNuYGaem2Zs4C15X/26sDkV
        pILZICZPZ1i+I+ZHpbETsM+s9CCE7o14KQ2sdQ+OxxJKIRPN5GbFNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-29T02:53:07Z'
  mac: ENC[AES256_GCM,data:d9vswB5y3V/yvYrtJOkH1nfC0k426toiga4tZkYXieyL92TFC/YgE0qlmxizj1//2VlHUGzD0RxdG83GY8pykzwDQhabAnT01fcmNpdnzk0sb63S4gPAahO1IGkDW8qMUG3VBQfO/tl/dPBuekv+zHKUVmvNX5uu39TQMDAx+bA=,iv:I6VHIthOwyc8k6NFJkCixRJkBG1V+n8OxpSE6p1E2xk=,tag:+INn2WwFrKZGY/I5mW8Hig==,type:str]
  pgp: []
  encrypted_regex: ^(stringData)$
  version: 3.8.1
