---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: 1-deploy-infra-monitoring-metrics
  namespace: &fns flux-system
  labels:
    kustomization.flux.home.arpa/name: &tns monitoring
    kustomization.flux.home.arpa/sops: "true"
    kustomization.flux.home.arpa/substitution: "true"
spec:
  path: ./kube/deploy/infra/monitoring/metrics
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: *fns
    namespace: *fns
  targetNamespace: *tns

---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: 1-deploy-infra-monitoring-alerting
  namespace: &fns flux-system
  labels:
    kustomization.flux.home.arpa/name: &tns monitoring
    kustomization.flux.home.arpa/sops: "true"
    kustomization.flux.home.arpa/substitution: "true"
spec:
  path: ./kube/deploy/infra/monitoring/alerting
  interval: 1h
  prune: false
  wait: true
  dependsOn:
    - name: 1-deploy-infra-monitoring-metrics
  sourceRef:
    kind: GitRepository
    name: *fns
    namespace: *fns
  targetNamespace: *tns
