---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./kube-system-allow-all.yaml  # TODO Really needed ? Tricky to try...
  - ./flux-system.yaml
  - ./cluster-default-kube-dns.yaml
  - ./labelled-allow-egress.yaml
  - ./labelled-allow-ingress.yaml
