---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n prometheus-crds
  namespace: &ns monitoring
  labels:
    kustomization.flux.home.arpa/name: *n
spec:
  interval: 1h
  prune: false
  wait: true
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: *n
  targetNamespace: *ns
