---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/gitrepository-source-v1.json
metadata:
  name: prometheus-crds
  namespace: monitoring
spec:
  interval: 12h
  url: https://github.com/prometheus-community/helm-charts.git
  ref:
    # renovate: registryUrl=https://prometheus-community.github.io/helm-charts chart=kube-prometheus-stack
    tag: kube-prometheus-stack-60.3.0
  ignore: |
    # exclude all
    /*
    # include crd directory
    !/charts/kube-prometheus-stack/charts/crds/crds
