---
stringData:
  GOOGLE_SMTP_MAIL: ENC[AES256_GCM,data:JqLwbhQ0Lc/wlKkAGZkd64TisB6Z,iv:jt/G9RnozEgGfv/c89VLnWg5PhpAEO+CqlR+0uhwWIc=,tag:dL4jev9wm5bte1Q4GhZFlA==,type:str]
  GOOGLE_SMTP_PASSWORD: ENC[AES256_GCM,data:Bblnae/Fwz30xf7sLUfZdpqkVg==,iv:AQ3eSg0qtHTOWSr5aBcWuhNlck8zlL1d0jKJ7zk4WkI=,tag:DHEHEcrewg84uT28cKunuA==,type:str]
  DOMAIN_PUBLIC: ENC[AES256_GCM,data:RQ4dqCPHYKq/bRw=,iv:/qvLsJO+BBx4/KsnjvFZPRkeWmGSnx07OPHQN+p9BrE=,tag:SQxPUI/qVckM+oRU9xVXFg==,type:str]
  EXTERNAL_DOMAIN: ENC[AES256_GCM,data:F1D3DdyLGLzW+/8L,iv:bwTTsARUlrB3FTQbQYZZV5RihTkUgvPxkIHB/Nb7nmI=,tag:8Ru7IQ37AUkxkdSzmlFnTg==,type:str]
  IP_PUBLIC: ENC[AES256_GCM,data:0LtwtCzOlWmM2Ibayw==,iv:8CSgOfZQbOj9D1NJ+hHyAtPX6yQ62VMt75zLafcZJ0s=,tag:LquZ/hLXW1JjY7tSQXI1QQ==,type:str]
  ISP_ROUTER_IP: ENC[AES256_GCM,data:ZKRYADOkCWoD94Bc/w==,iv:H5KA3uHjZhMcgo/yOPAmT89aDzq6XX9DhjSe2csV5Kw=,tag:UsPJlcbl0m+ZbiSMACPa0A==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:0ksi5BoJFj6Wskb+tEanJEUknjSd,iv:3usGRnw4UCr3Ib9lBdtTX9svbTP12tqcUctWULfI/jw=,tag:yUF1u3nJJYgJOQ12GBkJKA==,type:str]
  HOMELAB_GW_IP: ENC[AES256_GCM,data:axz0Ic2CM92uL8qUHQ==,iv:yTSgXx9ghkVlULraWI5mqQaH2773fTUCoj9QvlagQV8=,tag:Li4n07ygjDPUu5bE3agyiA==,type:str]
  HOMELAB_PVE_IP: ENC[AES256_GCM,data:nbpHRwS7sXZCdL0Paw==,iv:Lz1MAKMzyh5MAgEYPvp6AYz/7ZtESFFJaUv72fzr0Cw=,tag:Ln5cReQ13ZHGqmxnT3dKQQ==,type:str]
  HOMELAB_TRUENAS_IP: ENC[AES256_GCM,data:CVTuG7CgkZ9ju37TkA==,iv:ghtFjiVcCdhs8/Fo2ajujyFBfTdGb6eVh0SuLnD9Hj0=,tag:2hCkPdGYkhdUzgOON2Nd8g==,type:str]
  BARMAN_B2_BUCKET_NAME: ENC[AES256_GCM,data:OynGIzmsltEtzdw=,iv:9I1bafhXnS5IcKFpmoD4niGhipzyBpPrMg3LaQEQlXk=,tag:l+boBB5Xk3A8LNJaUQZKpg==,type:str]
  BARMAN_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:73wp3TO0NM9eM59PHbfgb3Gcf0jIbd8pqA==,iv:FPg+UwBVPW5Np0uNV6OeiaA1MssEZfw2nb0TL2PDC60=,tag:KKkMo8BS/Emamht/WpzsDA==,type:str]
  BARMAN_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:o6gsbAONW/5IH/p3KZVla0sTeqfgJuBaugrNbEKDMw==,iv:r9Q0r623EkaHCgwJL1nuHnMZd1B54q0wjbs3GjmiFRo=,tag:3LN/tw0cmBlfD9VQfQo0+g==,type:str]
  K8UP_B2_BUCKET_NAME: ENC[AES256_GCM,data:h00Yu8w3igM1Rp7lT2X5,iv:8OnvLJ09KI0pBWQzFk1iVTw5J7lXMRuptqkZEqCo3Hs=,tag:ymZgl/IPPH+GSgnAjC9Jlg==,type:str]
  K8UP_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:ETK0xufjKtEsYHEvb92IPPz8nOMlN4YPMw==,iv:SFzMm56NYaCQDbjIbyToQ7POOIBDiTUX82VKm/Deo/E=,tag:GRei/bP8pB/VTII1s0QYAQ==,type:str]
  K8UP_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:9V7QjUC2oKB2pZPHH/8T9QvOxAMn2Ml5E3847Ocizg==,iv:N20TFrH0CiQWOPPxVBJ8yqIl5a151QaZoXktXv7gIOg=,tag:ZgLue+XILi9WE/mXXlSPKg==,type:str]
  K8UP_RESTIC_KEY: ENC[AES256_GCM,data:efWQesl5pWTMCGXGnWvEt9Mvvk6r8xwoCFnUCXwhh7GJBd2B,iv:cto1Qwo9AposnGg41oMUjX91yKyxgUsf5S8jdRcpCTU=,tag:1bzdS5k1ub32+VYBEfnRVg==,type:str]
metadata:
  name: steropes-secrets
  namespace: flux-system
kind: Secret
apiVersion: v1
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwbWNZUEpwMDFhWDYxWE0y
        c3pieXcxL0tZTXBEVVdpQmlNbEhhaitlTkNRClkxK2QyRVhZN1ZHcFJ1QlZvQWRF
        WEltSklDMURLc2pCcXhiS3hDYzN4dUUKLS0tIDBsa2NrUjBlMlVwSkJNWEJmV1I4
        dXFNNllwRUNoazd6a0RLaHhmMStzSUEKTKDlq4uohZcABFCvPHvwzidSYELAlz4t
        eHw9s54G7VcJHoFb0Ez53ATOEzakhlp9HY4u9kzRUcAQw1BH9HuGqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-31T17:40:48Z'
  mac: ENC[AES256_GCM,data:VqnKwdVtZF2pB3o4f4VhI3r50lVGr45TqXSeVujNgPSb3UUkWN3lhysr+nGfn1d5ziv/ALNFL5cB8zAbWpl1+bXTLwRg6GF5igCk1/claIj5euxIHz6Tq0PGnRsPMIcklUNO+TSSDxfifAuXiF0jDC5hloJVFFMqYsR2o7N5CpI=,iv:aQAOBh0S6ecdQu0jAc+yAhiZvTwI8lWx+5nKpCvJBZw=,tag:OT+dKN5tSS5gXbe6zvjxXw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
