---
stringData:
  GOOGLE_SMTP_MAIL: ENC[AES256_GCM,data:h8+OHk9vd/urTRfHSlm2c7eSwSes,iv:tGk92wq1xzlJQojhJbt1RHVbm6quPQbq0TAylFk5GT4=,tag:8MWJQ8Gk54y6xpO0p1MraA==,type:str]
  GOOGLE_SMTP_PASSWORD: ENC[AES256_GCM,data:DCrgh3a8R3z9R/B/OlsB/Nl5sA==,iv:v+qwbjUvetdVLmcWHErHfCI4auMyMalJLkVp5E/5o3g=,tag:4GqPVZJeT6DtkLRGr3CHnA==,type:str]
  DOMAIN_PUBLIC: ENC[AES256_GCM,data:o8AviCram3xobjk=,iv:yJYJ/cL7sdZ9ndfBWpVfZZPaC3iArxYXYX/tvbVDqAs=,tag:o+wVwjZhn/OdkKT2LimAig==,type:str]
  EXTERNAL_DOMAIN: ENC[AES256_GCM,data:qYjYj17zf0RiT/6C,iv:9AmkQ7RXOLbN9ZzDkjen4OmVFTI95qWM1Gfe5OrfrNk=,tag:3MsUSdRo13B558xVNQY+8A==,type:str]
  IP_PUBLIC: ENC[AES256_GCM,data:oDyQqYIdYOVhfyZfjw==,iv:PFHpbcC5mYSn3fpvBR5SeRU675d7fqK7KgJQGTVNV/I=,tag:IO66sviWa0P0wTKsIgPeGA==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:hYVb2qQ+xdQKpsxaCL2nDSCLIMIc,iv:XYFCU+gInMbdVpfEuFiFO8xMXG3igoM4EWrlddtpAi8=,tag:mngnCPV4mX4Iv2hv8mgxpw==,type:str]
  HOMELAB_GW_IP: ENC[AES256_GCM,data:h24aax9ZNVJinKSm0w==,iv:C6OnzfubjMWbN+ykZxcY5GgkICOxU+qlwePSOCC8tm4=,tag:MREv2C1Psmqn6uJqXu/Hhw==,type:str]
  HOMELAB_PVE_IP: ENC[AES256_GCM,data:zTBKgjNkcjAxvQ+PRg==,iv:jfr1ieTtEBOMt+UUxVQZ32bCbF7MMwcoZNoyA+OmfzY=,tag:5fU8r5pAbJmvGwC278kq2g==,type:str]
  HOMELAB_TRUENAS_IP: ENC[AES256_GCM,data:COtNj1edUYhlHJ7mYA==,iv:Uf8PweGXFz8qirEsLfQuqU3tpYbcT47OX28c/Tw+hFk=,tag:qNxH+EZavlkL92zP2AVF+A==,type:str]
  BARMAN_B2_BUCKET_NAME: ENC[AES256_GCM,data:hzSy1UD+0+0sQ8k=,iv:KRa6EVYjQZc7OPXMMALRh3IJFj/PP9sW8bDVR5YDPtY=,tag:+/Vitoj52cQMaVt2vmyeWQ==,type:str]
  BARMAN_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:qc13Ns8tNup4fpa2WNxmrTQWTUNrvSxCow==,iv:gNrkxDnLNVzZhbHU9zz9uS9CmiHCdwowKN8K8lU06nM=,tag:jXTDIgGYy1sLARk6C7QowA==,type:str]
  BARMAN_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:jgxN7EccjyBL2JDgOvXVduAaymvAlmOyiH77ytbMEQ==,iv:WDssb6yiY4/eFoY1JLEz4oCseZ5UGKZ04j44U2NeagE=,tag:nIbUPicVZrRvB+jGByelBw==,type:str]
  K8UP_B2_BUCKET_NAME: ENC[AES256_GCM,data:eQdttjHfQ+/FlF6ixyNQ,iv:8WeZmQ8Iy5qwpdqbVRbhV/ZGimi5CTTBP42DRsY512g=,tag:pykLvb2UXCjvWtS7O7o44Q==,type:str]
  K8UP_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:ZWVJg0orFz2mMbIjaPMDfb9V+xe0Rg9kew==,iv:r7oNn80QGhr3S1Bs3zD09ihU11TYf6zpYuFqqJj5100=,tag:ZqwVTh/yBDxTtyYpw84PHA==,type:str]
  K8UP_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:Isw46bwi65QiniEiqgoiWWXWR8kkWhULlk3fk5u5mA==,iv:y9p9QiF1TfQ45wh5vKDiTJxMv+DQyH5dFkkJYslR0V8=,tag:ZDv9/phX6AAgAh31mVKBEw==,type:str]
  K8UP_RESTIC_KEY: ENC[AES256_GCM,data:4FzE2S/MCC7ScAjV/6oOmzT1UQnrB08HsdI6o2vpW6gvUf9I,iv:+eYuUkJ3/ye40nQ683ir7Ua5uvdZWyR8zG67pvRL144=,tag:d2pj2mtLQPuI9QAGUFeeaA==,type:str]
metadata:
  name: steropes-secrets
  namespace: flux-system
kind: Secret
apiVersion: v1
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSaUZ3RkE5UWVEblFTdW44
        TUM1bnJxUEprdXE4Q2w3cU4vNXFGZ0dqeFN3Ck8wRnp0NlFEY2hZbDF1SVc0emlL
        ZkpvdmIzdlRyeFh4WEh3ODNLL3MwenMKLS0tIElEY2FpMzJPdThOcEdlWmpIVXRk
        aTRLaFRUYTljbkJ3WmhDcGVKU2xQa3cKR12Sb9UBjfxnzbnmaXnCAbehljjaTAve
        xx8HVQB7xlSoYuo+vyx2BadKizOE6bo/zdrM1djERHnzkbYmyOlXyw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-08-29T17:46:00Z'
  mac: ENC[AES256_GCM,data:JkOIUTCyGr/QPCPI0Vf2VToAbvTOccYbyMy5mAzc5aYXw9ACmBaR3ni9k8BJC2GZyd7Pn8eYERu/l7jZ1pgBhS6EFNcZvTajBf3laHMfetHrMYRgV2N7BbR2rt9ZwjM7IpQ48LTCIBrfQtOKmBDGwvaXI7jSdrcWdzW11CPmqPY=,iv:1NUpsB9iSbzV47+6JCFJo83qKKe0ZlPYuSYS0Slph4c=,tag:CyJOsh2YS4UYVM0EJAyEbQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.9.0
