---
stringData:
  GOOGLE_SMTP_MAIL: ENC[AES256_GCM,data:E359nXCRrmeOcq0A9ZHToOh1H37j,iv:A9Ju1vqesixBAcB1duyANx5VcScAHGJX7jKPC6ibyRM=,tag:jqWCtQNjia84cP+pTPOYeA==,type:str]
  GOOGLE_SMTP_PASSWORD: ENC[AES256_GCM,data:kTkTGOePcwn6Bkaf5hrjW9z9Gw==,iv:kAmknXweRAmVSGwvZeI8zRuXUGq9D8Sp8S9f/VsbY18=,tag:tjl2GD9u6dqBxRibQQs3AA==,type:str]
  DOMAIN_PUBLIC: ENC[AES256_GCM,data:Rrl3djPRUNJeNjk=,iv:er+tNUMaRwDFPmqjP2pWeePrNWz8jF0jYQsEuc+tcr4=,tag:YEdaR6WruFvUDXlkvuYP1A==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:3hZdJrgAmI9Ni2YNvvNm9dTCOC/s,iv:LlS7M5nHe/7y40eTcPS8hLN+AGUP/+E4Wd/EVvdg7+E=,tag:mpC+y3B9zW5WhxGoJ1uEdA==,type:str]
  HOMELAB_GW_IP: ENC[AES256_GCM,data:sbDe7GEXime0Sevv3Q==,iv:iE5b7hKXpS8vF7fe7uuPMgdQxfVSHtr7RtMvGqIYiNA=,tag:lNlVC+dQ0kgOyXtOglVlAQ==,type:str]
  HOMELAB_PVE_IP: ENC[AES256_GCM,data:oIqPnLaNr1xvlwFtqQ==,iv:BIrLDK7xekyyT1NULFObHP5V4KyeWeGtrBhYFjVRuIY=,tag:uhrDsGpRbxwBt38n2m1Oxg==,type:str]
  HOMELAB_TRUENAS_IP: ENC[AES256_GCM,data:qkhpp2gzfhUUwwms5A==,iv:yxHE9W6VaKsOaW4Z5BdWKkquAcniOo20AB2va1ynE+w=,tag:aeUh1vExVL/dr3DOy2Fg0g==,type:str]
  BARMAN_B2_BUCKET_NAME: ENC[AES256_GCM,data:wMQEZY+L406Aqsk=,iv:00hsKK19QD2rSMIRCdPzl2Juba7rAm1VeeX/0CrG1G4=,tag:65XrVLfrcZtCkJzlIBEApQ==,type:str]
  BARMAN_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:S9C0ICR5qvtoyOIltdiwquihxOKGusxCGg==,iv:X1mhft4ulfdciKMOmZzevRMa9vNESjtyQ0cZiW2k3tU=,tag:L7wWtWCUg4BuvmTLYu3ieQ==,type:str]
  BARMAN_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:qYNiHCF7gfBb7631B5F8ReQ71JWlllQSgms4gcA+/w==,iv:am8wmhAmmwrdiOPgBr1stoYdIWG/3d1xdAgq+soCJKQ=,tag:3W7htKjQIwddkbZCjBffOw==,type:str]
  K8UP_B2_BUCKET_NAME: ENC[AES256_GCM,data:KVVZnZT7mTJvZtCZKZfb,iv:4j8D7AJ/NOpdX5w4Vr2d9bjN7W40hDGzaEcDoF3mIew=,tag:T+uWsP0nuOn3PfKUKlQ5vw==,type:str]
  K8UP_B2_ACCESS_KEY_ID: ENC[AES256_GCM,data:IJ1hFfXTnatkqaU9dLZUuZ0IBw19iDlqMg==,iv:WUeP7u1z9tvcRxkw7jnueM12Vq1u/HaCJVWvQeWDhCU=,tag:rZ/o2k7Pi9nbHU1IrFqEtQ==,type:str]
  K8UP_B2_ACCESS_KEY_SECRET: ENC[AES256_GCM,data:b4svdIklw5kf9SAXn8z0gT4fEuRaWuactD5py5DjXg==,iv:a7mix99CcjunWvYAFMlAd2QWWSxvHjNg19ByrayRSDw=,tag:mGjc5ciy9o42Wgwr2tywbQ==,type:str]
  K8UP_RESTIC_KEY: ENC[AES256_GCM,data:CEMZjMle73whkii7c0Mvg/BJqEvdf9tFMlwPrDWDOoQuOtWp,iv:hhbjjcDuqEzYg3H0tVDK/j56PMZLRuyU83MggJ9rquE=,tag:zvzi6Z5kPlCtAh0eS02qyA==,type:str]
metadata:
  name: steropes-secrets
  namespace: flux-system
kind: Secret
apiVersion: v1
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1SHJLZkFrazdYcVhOa3Ni
        V1ErTStnTnJPaDVzSUJVZ1d6cDM5T3dLVTNrCjVka296ZWNuMFNLc0Q3TlJwRzg3
        bEtDRmtVa09ITXoyMWJraDVRRmtPeW8KLS0tIEgwYTk4TXg4ZGdFT2V4RG41Y2tr
        aHR4bmdCZTJnTmRaRUJXbGM5eVRkcUkKxQfSVzL9BIVppVhRdpy0DUx8hfDb5Vm1
        5PyZ+Xbh4SZUTlOu7Voy7deYdtDjgu86bMcdJMjpT62kpHZfsVZHXw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: '2024-06-25T18:12:30Z'
  mac: ENC[AES256_GCM,data:RAk8+dtEGiMeFqeQf7w8XPSDBF/J366RrXb5Yf0pAkjco7RYo3VwvvHhG9Dy6MdHba9aTPF6En1MkaUwtYE3z3sgIuK68fVOd/3s/OaRU0rDtCpVLbrsBzWHzIg4gY+VvleXNPlPS2vZ7jl7YPm1ugjCbmMIwEQOg+ElAeTXx4w=,iv:kRqbJBieh6RKVWT+h+YJHqghWIaT4rfHFGWCxVXwSjM=,tag:tsNMDcpX98w3O3qaqhemKA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
