stringData:
  DOMAIN_PUBLIC: ENC[AES256_GCM,data:lWhOEVZVEirqzo0=,iv:IVnmNRLsVqYKqBdjkkIcvP47h+o43C4KxHY0CVCXr7U=,tag:jriqkCCu33KaJkkzsIOtvw==,type:str]
  ADMIN_EMAIL: ENC[AES256_GCM,data:yU6w2TPc2iDWQYWvtpd2HecglQgr,iv:/uuroTCV3IMvAQ/Dqfi3L+EVcqYcAAElVAXSVeSiezM=,tag:moJ7lny2J1WHocrmrzK8Mg==,type:str]
  HOMELAB_GW_IP: ENC[AES256_GCM,data:VKUQ6eeS5QtFhjknTA==,iv:hQXq7oO44Yy55scymR+ifjvwNAiz0Oaz2x2IAD0Al+M=,tag:dpfPwv8QluVDds5w7wO6xw==,type:str]
  HOMELAB_PVE_IP: ENC[AES256_GCM,data:LXYGr+ubMi5R5qgwqg==,iv:rgkeWvZd1u1IcuxM0jnvi1f68CMkvdyTvDR46FW8JsY=,tag:t7q3j21tSxus2mjUdi+7xQ==,type:str]
  HOMELAB_TRUENAS_IP: ENC[AES256_GCM,data:I47g2OneNbFuYgIU5A==,iv:61ZnASWyYtq1gEN95xmFejLb35sIYlDyFOtX55HHeIY=,tag:9wGW3LzZDpVPBqflAujtOw==,type:str]
metadata:
  name: steropes-secrets
  namespace: flux-system
kind: Secret
apiVersion: v1
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1430al9hlrscfugjgpyexe0se3wsc2l6aqsu55tah47h42r6pwpcsu9vf52
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYZWo2Tng5S3dDcXEwMTlz
        d3VQbGpUUmRJWFRqakMweVFJTWxYcFdtVVJVCkpEcHJUdHFBaXMyWStTQms1Zmli
        eVJ3dXZSR3lUTEJYSkFZQWRvTlcvVUkKLS0tIGFRRUxFRlhoaDhaOStVTjdwOVZ3
        TFFkeGpmaW9VbCt0UHhJMDBwTy9uSkEKMdp+4gUosocua0Xn+wZJCk6pWoGE0lO4
        5Hlv/KPnREXrpXTAfSLNm8eSzLccfS85+1xMbGXPzKsVdjt4sT/M8w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-06-23T16:37:08Z"
  mac: ENC[AES256_GCM,data:vvdF8ux/2ToT/YrZD0AFcci1IltgMu1fy21wdKBqs3oEZT7zD3Jgdv5edsNCeGoGvpOfh1aOFPR7q0C7wHKJbp9IQXSGw8cUVCmdSN+641FXougmqHxZiatuqBbqy/lCIsIEME+LnX/yVL2suNr70v2OczstunzBYXvfgMLLJzU=,iv:XZOL6UU5Ms9b0Mm4PgYku5KPjZQ4IzZm5PpuUHEJzCE=,tag:ZBoD3+l0tgjazcpmEryTjA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
