---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 0-deploy-core-1-kube-system
  namespace: &ns flux-system
  labels:
    kustomization.flux.home.arpa/name: &tns kube-system
    kustomization.flux.home.arpa/sops: "true"
spec:
  path: ./kube/deploy/core/1-kube-system/components
  interval: 1h
  timeout: 10m0s
  prune: false
  wait: true
  sourceRef: # ref ../../../flux/flux-repo.yaml
    kind: GitRepository
    name: *ns
  dependsOn: []
  targetNamespace: *tns
