---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 0-deploy-core-1-kube-system-cilium
  namespace: &ns flux-system
  labels:
    kustomization.flux.home.arpa/name: cilium
    kustomization.flux.home.arpa/sops: 'true'
    kustomization.flux.home.arpa/substitution: 'true'
spec:
  path: ./kube/deploy/core/1-kube-system/cilium
  interval: 1h
  timeout: 10m0s
  prune: false
  wait: true
  sourceRef:  # ref ../../../flux/flux-repo.yaml
    kind: GitRepository
    name: *ns
  dependsOn: []
  targetNamespace: kube-system
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: 0-deploy-core-1-kube-system-metrics-server
  namespace: &ns flux-system
  labels:
    kustomization.flux.home.arpa/name: metrics-server
spec:
  path: ./kube/deploy/core/1-kube-system/metrics-server
  interval: 1h
  timeout: 10m0s
  prune: false
  wait: true
  sourceRef:  # ref ../../../flux/flux-repo.yaml
    kind: GitRepository
    name: *ns
  dependsOn: []
  targetNamespace: kube-system
