---
apiVersion: v1
kind: Namespace
metadata:
  name: victoria-metrics-operator
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: grafana-operator
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled

---
apiVersion: v1
kind: Namespace
metadata:
  name: k8up-operator
  labels:
    kustomize.toolkit.fluxcd.io/prune: disabled
