---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n minio
  namespace: minio
spec:
  interval: 1h
  releaseName: *n
  chart:
    spec:
      chart: *n
      version: 14.6.13
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  values:
    podLabels:
      traefik.home.arpa/ingress: allow
      sso.home.arpa/egress: allow
    mode: standalone
    auth:
      rootUser: ${MINIO_ROOT_USER}
      rootPassword: ${MINIO_ROOT_PASSWORD}
    defaultBuckets: steropes-pg
    networkPolicy:
      enabled: false
    persistence:
      enabled: true
      accessModes: [ReadWriteOnce]
      size: 100Gi
      annotations:
        k8up.io/backup: 'true'
    volumePermissions:
      enabled: true
