---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n alerting-vmalertmanager
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/infra/monitoring/alerting/vmalertmanager/
  interval: 1h
  prune: false
  wait: false
  healthChecks:
    - apiVersion: apps/v1
      kind: StatefulSet
      name: vmalertmanager-main
      namespace: &tns monitoring
  dependsOn: []
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: *tns

---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n alerting-vmalert
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/infra/monitoring/alerting/vmalert/
  interval: 1h
  prune: false
  wait: false
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: vmalert-main
      namespace: &tns monitoring
  dependsOn:
    - name: alerting-vmalertmanager
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: *tns

---
apiVersion: kustomize.toolkit.fluxcd.io/v1 # yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
kind: Kustomization
metadata:
  name: &n alerting-vmrules
  labels: &l
    kustomization.flux.home.arpa/name: *n
spec:
  path: ./kube/deploy/infra/monitoring/alerting/vmrules/
  interval: 1h
  prune: false
  wait: true
  dependsOn:
    - name: alerting-vmalert
  sourceRef:
    kind: GitRepository
    name: &fns flux-system
    namespace: *fns
  commonMetadata:
    labels: *l
  targetNamespace: monitoring
