---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &n prometheus-node-exporter
spec:
  chart:
    spec:
      chart: *n
      version: 4.37.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
  values:
    prometheus:
      monitor:
        enabled: true
